### ISSUE TITLE
Google RPC add-on is building into an incorrectly named folder for Electron

### ISSUE THREAD

**Issue by mattcollier** [googleapis/nodejs-speech#11]
This has to do with [electron-speech-recognition](https://github.com/mattcollier/electron-speech-recognition).  The build ultimately works properly, but the build binary for [@google-cloud/speech ](https://github.com/googleapis/nodejs-speech) folder must be renamed as shown here:
https://github.com/mattcollier/electron-speech-recognition/blob/master/rename-grpc-binary.sh

I don't know if that's a problem with the `grpc` node-gyp configuration, an issue with electron-rebuild or what.  Can anyone point me in the right direction?

#### Environment details

  - OS: Debian 9
  - Node.js version: Electron 1.6 and 1.7
  - npm version: 5.5.1
  - @google-cloud/speech version: 1.0.0

See also: https://github.com/electron/electron-rebuild/issues/217

**Comment by stephenplusplus** [comment]
It sounds like you made further progress with this in the other issue? If not, I would recommend opening an issue on the [grpc](http://www.gitnpm.com/grpc) repo.
