### ISSUE TITLE
Can't get the package to work on a Raspberry Pi Zero

### ISSUE THREAD

**Issue by alexdufetel** [googleapis/nodejs-speech#12]
I run into an "illegal instruction" error when requiring the package in a node file. I have been able to successfully use the library on a RPI 3, but not on the RPi zero. I believe this problem is likely related to the RPi zero's different processor architecture (ARMV6).

#### Environment details

  - OS: Raspbian 9
  - Node.js version: 8.9.3, 8.0.0, or 7.10.1 (same error with each version) 
  - npm version: 5.5.1
  - @google-cloud/speech version: 0.10.3 or 1.0.0 (same error with both)

#### Steps to reproduce
  - install node on a RPI zero and run the demo sample

**Comment by stephenplusplus** [comment]
@alexander-fenster -- thoughts on how to approach this issue?

**Comment by mattcollier** [comment]
@alexdufetel you should find the native binary build into a sub-folder found here: `node_modules/grpc/src/node/extension_binary`  The folder name should look something like `node-v53-linux-x64-glibc`.  The folder name includes the node 'module version' which you can cross reference [here](https://nodejs.org/en/download/releases/).  And it should also indicate the architecture it was built for, `x64` in this case.  What is the name of your build folder?

**Comment by alexdufetel** [comment]
Thanks for following up. I have two folders in node_modules/grpc/src/node/extension_binary. I assume this is linked to me trying out with different versions of node with nvm. 
The folder names are node-v51-linux-arm-glibc and node-v57-linux-arm-glibc.

**Comment by alexdufetel** [comment]
Looks like this is the root cause : https://github.com/grpc/grpc/issues/13258
Apparently fixable using npm rebuild --build-from-source grpc 
will give it a try

**Comment by stephenplusplus** [comment]
I'm going to close the issue, as it doesn't seem we can do anything from this end. Feel free to keep discussing here (although in the gRPC issue may be better). If there's something we need to fix, I will re-open.

**Comment by alexdufetel** [comment]
Quick update to confirm that rebuilding the GRPC library using the command` npm rebuild --build-from-source grpc` solved the issue for me

**Comment by williamw** [comment]
+1 this worked for me w/ assistant-relay 3.2 on a raspberry pi w/ an ARMv6 CPU (not sure which model I have specifically).  Just had to run this command within the assistant-relay directory: npm rebuild --build-from-source grpc

**Comment by alexander-fenster** [comment]
@williamw This issue is too old. Since the time it was created, the library was switched to `@grpc/grpc-js` which is pure JavaScript and only requires Node.js >= v8.13.0, >= v10.10.0, or any newer. And, indeed, there are no problems running this on Raspberry Pi (I did it personally) :)
