### ISSUE TITLE
Run Time Error- Can not find Module "Child_Process"

### ISSUE THREAD

**Issue by KyawMyoKhant** [googleapis/nodejs-speech#122]
I am using Google Speech API and Note.js.

I already imported the necerssary Client Library but still hitting Error. 

     const client = new **speech.SpeechClient()**;

I think this is were the error is

![capture](https://user-images.githubusercontent.com/41543251/43046002-6318431a-8df5-11e8-9930-84e6ea11bb47.PNG)

**Comment by stephenplusplus** [comment]
For now, I don't believe we intend to support Webpack integration. Related issues: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1821

You can subscribe to this issue in case that ever changes: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/531
