### ISSUE TITLE
I am having trouble installing the latest Google cloud client library for node.js

### ISSUE THREAD

**Issue by qunliu** [googleapis/nodejs-speech#124]
I am trying to install the Google cloud client speech library for node.js and having trouble to install it. I run: npm install --save @google-cloud/speech, it can't find  https://iojs.org/download/release/v1.7.9/iojs-v1.7.9.tar.gz as shown in the screenshot below. If you go to this site (https://iojs.org/download/release/) and apparently there is no v1.7.9 can be found there. Even though I am showing the screenshot on a macos, but I tried the same thing on Windows, it failed the same way. 

![image](https://user-images.githubusercontent.com/5871654/43170383-da5292ae-8f72-11e8-91fe-c78257854ddc.png)

#### Environment details

  - OS: macos 10.13.2
  - Node.js version: 8.9.1
  - npm version: 6.2.0
  - `@google-cloud/speech` version: can't install, don't know.

#### Steps to reproduce

  1. run: npm install --save @google-cloud/speech
  2. can't install: installation fails when installing https://iojs.org/download/release/v1.7.9/iojs-v1.7.9.tar.gz which is not found.

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Hmm, this is a weird one. We don't have a dependency on io.js. Could you create an empty directory to work with, run `npm init -y && npm install @google-cloud/speech` and let me know if you still see the error?

**Comment by stephenplusplus** [comment]
Phew! I think there must be another dependency that depends on io.js. Check the `package.json` in the folder where the installation fails, or even better, the `package-lock.json`, if you have one. Scan it for `io.js`, and you can at least track it back to the problematic dependency that requires it.
