### ISSUE TITLE
circleci lint failure

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-speech#126]
Linting failures claiming we cannot support `async`/`await` in samples for Node 6. That's true, I guess something should be changed in the `engine` section or somewhere else.

https://circleci.com/gh/googleapis/nodejs-speech/3622

All master CI being red is very dangerous situation.

**Comment by alexander-fenster** [comment]
Oh, I've just noticed it happens for a lot more other packages as well.

**Comment by broady** [comment]
Looks like CI is passing now.

Safe to close, @alexander-fenster ?

**Comment by alexander-fenster** [comment]
Closing. (CI still fails but different task and for a different reason :) )
