### ISSUE TITLE
How to stop streaming recognize?

### ISSUE THREAD

**Issue by anjucheran** [googleapis/nodejs-speech#135]
I am sending data from frontend to backend using an `AudioContent` through a websocket. I use stream recognizing and I want to stop streaming when one result has `isFinal` `true`. I couldn't stop it therefore server will be down because of timeout.

  OS: Ubuntu 18.04 lts
  Node.js version: v10.7.0
  npm version: 6.1.0
  `@google-cloud/speech` version: 2.0.0

How can I stop stream to google speech?
Thank you!

**Comment by stephenplusplus** [comment]
Would you mind preparing an example reproduction case? Thanks!
