### ISSUE TITLE
Transcription not printed

### ISSUE THREAD

**Issue by prasadnarasimhan74** [googleapis/nodejs-speech#14]
#### Environment details

  - OS: windows 7
  - Node.js version: v9.2.1
  - npm version: 5.5.1
  - @google-cloud/speech version: Latest

#### Steps to reproduce

  1. executed node recognize listen
  2. D:\speech\sample\nodejs-speech\samples>node recognize listen
Recording with sample rate 16000...
Listening, press Ctrl+C to stop.
Recording 4163 bytes
Recording 1385 bytes
End Recording: 64.330ms

Got  the above output. Expecting the Transcription.

**Comment by stephenplusplus** [comment]
I'm sorry to have this hanging around for so long. I have attempted to reproduce this multiple times, however, I'm having trouble even getting up and running. My Windows environment has some quirks which is making this more difficult to test. Have you been able to make any progress on this?

**Comment by stephenplusplus** [comment]
I hope this has worked out, but please let us know if this is still an issue.
