### ISSUE TITLE
Delay in using alternative language codes

### ISSUE THREAD

**Issue by alisher-agzamov** [googleapis/nodejs-speech#144]
#### Environment details

  - OS: cenots 7
  - Node.js version: v6.11.3
  - npm version: 3.10.10
  - `@google-cloud/speech` version: ^2.0.0

#### Steps to reproduce

```
var streamingConfig = {
    config: {
        encoding: 'OGG_OPUS',
        sampleRateHertz: 16000,
        languageCode: 'ru-RU',
        profanityFilter: false,
        enableAutomaticPunctuation: true,
        maxAlternatives: 1,
        alternativeLanguageCodes: ['en-US']
    },
    singleUtterance: true,
    interimResults: true,
    verbose: true,
    timeout: 600
};
```

When I'm using the alternative language codes in streamingRecognize the partial result returning with a long delay. All partial results are returned almost together with the last (isFinal: true) message.

**Comment by kinwa91** [comment]
Forwarded question to Speech team: https://issuetracker.google.com/120438287
