### ISSUE TITLE
How do I force streamingRecognize to error when network is unavailable?

### ISSUE THREAD

**Issue by kervurn** [googleapis/nodejs-speech#147]
I'm struggling to get streamingRecognize throw an error if the network is not available. 

Right now it seems like it is just waiting the full "deadline" which appears to be 1000 seconds, until it throws the DEADLINE_EXCEEDED error.

I imagine there could be an option to shorten the "deadline", but this would not be a full solution because I would like to get the UNAVAILABLE error (or the expected no network error), so it can be handled appropriately.

My implementation of streamingRecognize looks like this.

``` 
    // this code lives in a class;
    this.speechClient = new speech.v1p1beta1.SpeechClient({keyFilename: path.join(__dirname, 'keyfile.json')});

    const AUDIO_CONFIG = {
      encoding: 'LINEAR16',
      sampleRateHertz: 16000,
      languageCode: 'en-US',
    };

    let request = {
      config: AUDIO_CONFIG,
      interimResults: true,
    };

    this.recognizeStream = this.speechClient
      .streamingRecognize(request)
      .on('error', (err) => {
        // not seeing the UNAVAILABLE error
        this.logger.error(`recognize error`, err);
      })
      .on('data', (data) => {
        // do something with the data
      })

    inputStream.pipe(this.recognizeStream);
```
#### Environment details

  - OS:
  - Node.js version: v6.9.5
  - npm version: 3.10.10
  - `@google-cloud/speech` version: 1.4.0

#### Steps to reproduce

  1. disable internet connection (e.g. disable Wi-Fi)
  2. invoke a previously working implementation of streamingRecognize
  3. observe results (no UNAVAILABLE error; DEADLINE_EXCEEDED error after 1000 seconds)

**Comment by JustinBeckwith** [comment]
@googleapis/ml-apis @beccasaurus so as it turns out, you can't assign an issue to a team 🤷‍♂️

**Comment by kinwa91** [comment]
There is a hidden setting to prevent the underlying gRPC client from retrying when getting `UNAVAILABLE` error from the server.

When you construct a client, you can pass a `clientConfig` object:

```js
const clientConfig = {
  interfaces: {
    'google.cloud.speech.v1p1beta1.Speech': {
      retry_codes: {
        idempotent: ["DEADLINE_EXCEEDED"] // in the default setting, "UNAVAILABE" is also listed a one of the errors where the client will attempt to retry on receiving
      },
      "methods": {
        "Recognize": {},
        "LongRunningRecognize": {},
        "StreamingRecognize": {}
      }
    }
  }
}

// Create the client
this.speechClient = new speech.v1p1beta1.SpeechClient({
  clientConfig: clientConfig,
  ...
});
```
