### ISSUE TITLE
enableWordTimeOffsets = true not working for streamingRecognize

### ISSUE THREAD

**Issue by bloodcarter** [googleapis/nodejs-speech#15]
enableWordTimeOffsets option yelds empty "words" array at least for streamingRecognize and al least for Russian. 

Env:
  - OS: Linux ip-172-31-16-252 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: v7.2.1
  - npm version: 3.10.10
  - google-cloud-node version:  @google-cloud/speech@0.10.3

Code:
```
var recognizeStream = Speech.streamingRecognize(
    {
      config: {
        enableWordTimeOffsets: true,
        encoding: self.inputFormat.encoding,
        sampleRateHertz: self.inputFormat.sampleRate,
        languageCode: "ru-RU"
      },
      singleUtterance: false,
      interimResults: true
    }
  );

recognizeStream.on('data', (data)=>{...});
```

**Comment by stephenplusplus** [comment]
Would you be able to put together a small repo with a sample audio file, that allows us to clone, run, and see the failure?

**Comment by bloodcarter** [comment]
@stephenplusplus looks like it works, but only after isFinal is set to true. Is that a bug? What if I need words boundaries immediatedly while getting interim results?

**Comment by stephenplusplus** [comment]
Unfortunately, I don't have many answers about how to use the upstream API. We are a very thin layer. You can get in touch with more experienced users / developers through one of the methods mentioned here: https://cloud.google.com/speech/docs/support

Sorry that I couldn't be more help on this one.

**Comment by jinyeng** [comment]
This issue is still happening. Any plans on fixing ?

![image](https://user-images.githubusercontent.com/58823520/73991569-87877400-491a-11ea-9474-ff000f606ea2.png)

**Comment by HMLarsen** [comment]
Any answers in 2021?

**Comment by dalynsw** [comment]
Still not working

info: transcript: {"callsid":"CAe280196639afed68c298bbc8b27530c7","content":"{\"results\":[{\"alternatives\":[{\"words\":[],\"transcript\":\"Good morning. How are you? I'm fine. And you\",\"confidence\":0}],\"isFinal\":false,\"stability\":0.8999999761581421,\"resultEndTime\":{\"seconds\":\"8\",\"nanos\":390000000},\"channelTag\":0,\"languageCode\":\"en-us\"},{\"alternatives\":[{\"words\":[],\"transcript\":\" want to\",\"confidence\":0}],\"isFinal\":false,\"stability\":0.009999999776482582,\"resultEndTime\":{\"seconds\":\"8\",\"nanos\":390000000},\"channelTag\":0,\"languageCode\":\"en-us\"}],\"error\":null,\"speechEventType\":\"SPEECH_EVENT_UNSPECIFIED\",\"totalBilledTime\":null}","createTime":1646557832403,"text":"Good morning. How are you? I'm fine. And you","timestamp":"2022-03-06 09:10:32","track":"inbound"}
