### ISSUE TITLE
Poor performance on streamingRecognize

### ISSUE THREAD

**Issue by bruno911** [googleapis/nodejs-speech#16]
#### Environment details

  - OS: (docker: google/cloud-sdk:latest) Debian based
  - Node.js version: v8.9.4
  - npm version: 5.6.0
  - @google-cloud/speech version: @google-cloud/speech@1.0.0

###########
The issue:

I had google speech working relatively fine 3-6 months ago. I haven't used it for a while, as I build it for a demonstration only.

Few days ago, I noticed it stopped working, so I did the usual upgrading of libraries, docker image, npm, etc. Now even if it works, it takes about between 40 seconds and 1 minute to return any text.

############

My architecture is as following
- Client: Browser, using socket io I stream to our server.

            stream1 = ss.createStream();

            navigator.getUserMedia({
                audio: {
                    mandatory: {
                        googEchoCancellation: "false",
                        googAutoGainControl: "false",
                        googNoiseSuppression: "false",
                        googHighpassFilter: "false"
                    },
                    optional: []
                }
            },
            function(o)
            {
                audioContext = new AudioContext,
                streamSource = audioContext.createMediaStreamSource(o),
                chunckSize = 4096,
                scriptProcessor = audioContext.createScriptProcessor(chunckSize, 1, 0);

                ss(socket)
                    .emit(
                        'client-stream-request',
                        stream1,
                        {
                            sampleRate: audioContext.sampleRate,
                            userId: that.config.userId,
                            languageCode: that.config.languageCode
                        }
                    );

                scriptProcessor.onaudioprocess = function(o)
                {
                var input = o.inputBuffer.getChannelData(0);
                    stream1.write( new ss.Buffer( self.convertFloat32ToInt16(input) ) );
                };
                
                scriptProcessor.connect(audioContext.destination);
                streamSource.connect(scriptProcessor);

            }, function(n) {
                that.ui.setState('notrecording');
            })

        this.convertFloat32ToInt16 = function(buffer)
        {
            l = buffer.length;
            buf = new Int16Array(l);

            while (l--)
            {
               buf[l] = Math.min(1, buffer[l])*0x7FFF;
            }

            return buf.buffer;
        }
`

- Server: Node.js in docker using nginx as reverse proxy

                var speech = require('(at)google-cloud/speech'),
                      speechClient = new speech.v1.SpeechClient({
                            projectId: config.google.auth.projectId
                      });

                request = {
                        config: {
                            encoding:'LINEAR16',
                            sampleRateHertz: sampleRate, //this comes from the browser
                            languageCode: languageCode
                        },
                        singleUtterance: false,
                        interimResults: false 
                    };

                        speechClient.streamingRecognize(request)
                                .on('error', function (e) {
                                    console.log(e);
                                })
                    .on('data', function (data)
                    {
                        socket.emit('recognized', text);
                    });

The error in the console, are because I am testing and everytime I leave it expire.

![selection_135](https://user-images.githubusercontent.com/5426300/35004557-6c3da390-fae8-11e7-9dec-dd4f270dd239.png)

Any ideas ?

**Comment by stephenplusplus** [comment]
Thanks for reporting. Are you able to isolate external dependencies from this sample and see the same performance loss? In other words, working with fixed data within a single Node.js script, not involving the browser?

**Comment by stephenplusplus** [comment]
@bruno911 please let me know if this is still an issue and you can address the above question. For now, I'm going to close as we haven't heard anything otherwise.
