### ISSUE TITLE
Error: 3 INVALID_ARGUMENT: Invalid recognition 'config': bad language code.

### ISSUE THREAD

**Issue by onofrioP89** [googleapis/nodejs-speech#173]
Hello,

#### Environment details

  - OS: Container-Optimized OS 68-10718.106.0 stable
  - Node.js version: node:8.11.3 and node:8.11.4
  - npm version: 5.6.0
  - Docker version: 17.03.2-ce, build f5ec1e2
  - `@google-cloud/speech` version: 2.0.0 and 2.1.0

#### Steps to reproduce

I've updated the client library from 1.5.0 to 2.0.0 and 2.1.0.

When I tried to use streamingRecognize from Speech.v1.SpeechClient(), I received 

```
{ Error: 3 INVALID_ARGUMENT: Invalid recognition 'config': bad language code.
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/app/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._readsDone (/app/node_modules/grpc/src/client.js:201:8)
    at /app/node_modules/grpc/src/client_interceptors.js:694:15
  code: 3,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: 'Invalid recognition \'config\': bad language code.' }
``` 

The configuration of the request is the same that I used with version 1.5.0 of the client library

```
const config = {
            config: {
                encoding: 'LINEAR16',
                sampleRateHertz: 8000,
                languageCode: 'it-IT'
            },
            interimResults: true, 
            single_utterance: true
        };

```
The error is found in both version 2.0.0 and version 2.1.0 of the client library.

#### Workaround
To allow my application to run again correctly in the GCP environment , I had to downgrade the library again to version 1.5.0.

Onofrio
Thanks!

**Comment by onofrioP89** [comment]
I think it can be related to the same problem that causes the bug https://github.com/googleapis/nodejs-speech/issues/170

**Comment by stephenplusplus** [comment]
Thank you for reporting!

@JustinBeckwith this is the error I was receiving locally as well with one of our sample tests. The language code is the same as it has always been, and still matches what the API docs show: https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.RecognitionConfig

Could something have gone wrong upstream with the API? Or some other change that we didn't hear about?

**Comment by JustinBeckwith** [comment]
Not sure :(  @beccataylor who can we pull in here?  @theacodes are we seeing reports in other languages?

**Comment by theacodes** [comment]
Not that I'm aware of.

**Comment by kinwa91** [comment]
Ran the python streaming sample and it completed successfully.

**Comment by kinwa91** [comment]
checkout v1.5.0 's `src/helper.js` on HEAD resolved the problem. I'm suspecting the culprit is somewhere in there 🕵️

**Comment by kinwa91** [comment]
It looks like the API cannot accept `streamingConfig` and `audioContent` in the same write..

Will there be issues w.r.t to error handling if I made this change to send `streamingConfig` as a separate write at the beginning? @stephenplusplus 

https://github.com/googleapis/nodejs-speech/compare/fix-streaming-recognize
