### ISSUE TITLE
v2.1.1 - still throws Malordered Data Received. Send exactly one config, followed by audio data

### ISSUE THREAD

**Issue by rowntreerob** [googleapis/nodejs-speech#198]
i have read over #176 and verified that i have v2.1.1 installed

and i still get the error ..

clearly the helper.js has the new code with the 

recognizeStream.once('writing',

Im not using node.pipe per all the examples .  
Instead im calling "requestStream.write([request.body])  "   from node express.route that handles speech buffer from my client to my back end. 

my code:
```
app.post('/speech', rawParser, function(request, response, next) {
    voiceAPI(request.body, function(error, speech) { })
}

var voiceAPI = function (data, callback) {

const speech = require('@google-cloud/speech');
  var client = new speech.SpeechClient({
  });
  var encoding = 'OGG_OPUS';
  var sampleRateHertz = 16000;  //per cloud speech opus mimetyp
  var languageCode = 'en-US';
  var config = {
    encoding: encoding,
    sampleRateHertz: sampleRateHertz,
    languageCode: languageCode,
  };
 const stream = client.streamingRecognize({
     config: config,
   }).on('data', function(resp) {
     console.log(JSON.stringify(resp));
     var speech = new Object();
     speech['transcription'] = 'blah blah is ans';
     return callback(null, speech);
   });

   stream.write(data); //buffer from raw parser
```
i also tried 2 writes 
   stream.write(config);
   stream.write(buffer);
getting same error. 

stdout: 
12:14:53 PM web.1 |  events.js:193
12:14:53 PM web.1 |        throw er; // Unhandled 'error' event
12:14:53 PM web.1 |        ^
12:14:53 PM web.1 |  Error: Malordered Data Received. Send exactly one config, followed by audio data.
12:14:53 PM web.1 |      at new ApiError (/home/rob/src/web-spch-v2/node_modules/@google-cloud/common/build/src/util.js:58:28)
12:14:53 PM web.1 |      at DestroyableTransform.recognizeStream.setPipeline.through.obj [as _transform] (/home/rob/src/web-spch-v2/node_modules/@google-cloud/speech/src/helpers.js:108:18)
12:14:53 PM web.1 |      at DestroyableTransform.Transform._read (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
12:14:53 PM web.1 |      at DestroyableTransform.Transform._write (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
12:14:53 PM web.1 |      at doWrite (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
12:14:53 PM web.1 |      at writeOrBuffer (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
12:14:53 PM web.1 |      at DestroyableTransform.Writable.write (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
12:14:53 PM web.1 |      at StreamProxy.ondata (/home/rob/src/web-spch-v2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
12:14:53 PM web.1 |      at emitOne (events.js:125:13)
12:14:53 PM web.1 |      at StreamProxy.emit (events.js:221:7)

**Comment by rowntreerob** [comment]
ill try to push a git project w the issue in it.

**Comment by rowntreerob** [comment]
got it working

**Comment by vin-ni** [comment]
@rowntreerob what was the issue?

**Comment by rowntreerob** [comment]
when i switched a node app from the file based ( sync ) recognizer to
'streaming' i got the err in title.

i took about 4 days to rip apart the samples for node && the api and
streaming works.  i dont know what was the cause of the error, but
obviously the streams and the helper classes underlying this api are kinda
complex , maybe bit brittle....

the goal is webpage that pipes to node back end that pipes to the streaming
api with 'interim' results

So that the origin webpage w getUserMedia(audio)  - shows the gapic or grpc
supported transpose as the mic is on and the person is speaking...

sounds so simple....

**Comment by rowntreerob** [comment]
ps

im using webpack 4.0 to build and that seems OK.

i just switched over to that too from gulp

**Comment by danajeremy** [comment]
I have exactly the same problem. How did you manage to solve it?

**Comment by dxh9845** [comment]
There are numerous examples on the web and yet I STILL cannot get this error to go away. Any guidance would be appreciated on how to solve this. @danajeremy

**Comment by callmehiphop** [comment]
@dxh9845 is your setup the same as OPs? If it deviates at all, would you mind sharing any details that might help us figure out what is going on here

**Comment by dxh9845** [comment]
I've tried copying this [repo ](https://github.com/vin-ni/Google-Cloud-Speech-Node-Socket-Playground) verbatim as well as using ES6 class syntax to manage the Google API. My attempt is [here](https://github.com/dxh9845/lecture-server). I should mention that @vin-ni 's repository works flawlessly. 

Here's how I call it from the client side - just getting audio from a web browser via the microphone, downsampling it, and sending it to the Socket. I've bolded the relevant parts.

**ScriptProcessor.js**
```
import SocketService from './SocketService';

export default class ScriptProcessor {
    audioContext;

    microphoneNode;

    scriptProcessor;

    bufferSize;

    socketService;

    recording = false;

    constructor(bufferSize = 2048) {
      this.constructAudioContext = this.constructAudioContext.bind(this);
      this.startRecording = this.startRecording.bind(this);
      this.stopRecoridng = this.stopRecording.bind(this);
      this.streamAudio = this.streamAudio.bind(this);
      this.endStreaming = this.endStreaming.bind(this);
      this.downsampleBuffer = this.downsampleBuffer.bind(this);

      // Open our websocket
      **this.socketService = new SocketService();**
      this.bufferSize = bufferSize;

      window.onunload = this.socketService.endStreaming;
    }

    /**
     * Construct the audio context off the window.
     */
    constructAudioContext() {
      // Create the Audio Context object from the Window
      const AudioContext = (window.AudioContext || window.webkitAudioContext);
      this.context = new AudioContext({
        // Non-interactive, we need to just send the stream as quick as possible
        latencyHint: 'playback',
      });
    }

    /**
     * Start recording from the microphone script processor
     * @param {MediaDeviceInfo} inputDevices - the recording input devices
     */
    async startRecording(inputDevices) {
      // Initialize the Google stream
      this.socketService.sendInitializeRequest();

      if (!this.context) {
        this.constructAudioContext();
      }

      // Create the microphone input source from our context object
      this.microphoneNode = this.context.createMediaStreamSource(inputDevices);

      // Specify the script processor with our buffer size with one input and one output
      // channel
      this.scriptProcessor = this.context.createScriptProcessor(this.bufferSize, 1, 1);

      // Link our audio processor event
      this.scriptProcessor.onaudioprocess = this.streamAudio;

      this.microphoneNode.connect(this.scriptProcessor).connect(this.context.destination);

      this.recording = true;
    }

    /**
     * Stop recording.
     */
    stopRecording() {
      this.recording = false;
      this.endStreaming();
      try {
        console.log(this.microphoneNode.mediaStream);
        this.microphoneNode.mediaStream.getTracks()[0].stop();
      } catch (err) {
        console.log(`ERROR unable to close media stream: ${err}`); // triggers on Firefox
      }
      this.context.close();
      this.context = null;
    }

    /**
     * Send the audio on the web socket
     * @param {AudioProcessingEvent} audioProcessingEvent -  audio processing event
     */
    streamAudio({ inputBuffer, outputBuffer }) {
      const inputData = inputBuffer.getChannelData(0);

      const downsampledBuffer = this.downsampleBuffer(inputData, 44100, 16000);

      this.socketService.streamAudio(downsampledBuffer);
    }

    endStreaming() {
      this.socketService.endStreaming();
    }

    // eslint-disable-next-line class-methods-use-this
    downsampleBuffer(buffer, sampleRate, outSampleRate) {
      if (outSampleRate == sampleRate) {
        return buffer;
      }
      if (outSampleRate > sampleRate) {
        throw Error('downsampling rate show be smaller than original sample rate');
      }
      const sampleRateRatio = sampleRate / outSampleRate;
      const newLength = Math.round(buffer.length / sampleRateRatio);
      const result = new Int16Array(newLength);
      let offsetResult = 0;
      let offsetBuffer = 0;
      while (offsetResult < result.length) {
        const nextOffsetBuffer = Math.round((offsetResult + 1) * sampleRateRatio);
        let accum = 0;
        let count = 0;
        for (let i = offsetBuffer; i < nextOffsetBuffer && i < buffer.length; i++) {
          accum += buffer[i];
          count++;
        }

        result[offsetResult] = Math.min(1, accum / count) * 0x7FFF;
        offsetResult++;
        offsetBuffer = nextOffsetBuffer;
      }
      return result.buffer;
    }
}
```

Here's the Socket Service for reference: 
**SocketService.js**
```
import io from 'socket.io-client';
import {
  AUDIO_CHANGE, START_STREAM, END_STREAM, CONNECT, MESSAGES, JOIN,
} from '../utils/events.types';


export default class SocketService {
    socket;

    constructor(socketPath = 'http://localhost:8081') {
      this.socket = io(socketPath);

      // Bind our functions
      this.setupSocketHandlers = this.setupSocketHandlers.bind(this);
      this.broadcastJoin = this.broadcastJoin.bind(this);
      this.streamAudio = this.streamAudio.bind(this);
      this.sendInitializeRequest = this.sendInitializeRequest.bind(this);
      this.endStreaming = this.endStreaming.bind(this);

      // Setup the handlers
      this.setupSocketHandlers();
    }

    setupSocketHandlers() {
      this.socket.on(CONNECT, this.broadcastJoin);
      this.socket.on(MESSAGES, data => console.log(data));
    }

    broadcastJoin() {
      this.socket.emit(JOIN, 'Server connected to the client.');
    }

    /**
     * Send the audio data on the websocket
     * @param {} audioData
     */
    streamAudio(audioData) {
      this.socket.emit(AUDIO_CHANGE, {
        data: audioData,
      });
    }

    sendInitializeRequest() {
      this.socket.emit(START_STREAM, '');
    }

    endStreaming() {
      this.socket.emit(END_STREAM, '');
    }
}
```

What I believe is happening is that, despite explicitly initializing the Google API over the socket in the `startRecording` function, it doesn't take and it sends audio before Google is ready. I've experimented with timeouts and delays on both the client and the server, and neither have worked. 

Sorry if this is overkill.

**Comment by rowntreerob** [comment]
FWIW   - excerpts from streaming STT on googcloud that has been in PROD for
awhile .

in a gist at :
https://gist.github.com/rowntreerob/c37cd52201c6d88d62355e58fcd91949

**Comment by riyashah17** [comment]
Still facing the same issue. Do we have a solution for this?
