### ISSUE TITLE
Can't make longRunningRecognize to work

### ISSUE THREAD

**Issue by mlumbroso** [googleapis/nodejs-speech#23]
#### Environment details

  - OS: Windows 10 and Linux
  - Node.js version: 6.9.1
  - npm version: 3.10.8
  - @google-cloud/speech version: 1.0.1

#### Steps to reproduce

  1. Using : 
```js
    var config = {
        encoding: 'FLAC',
        languageCode: 'en-US',
        sampleRateHertz: 32000
    };
    // The name of the audio file to transcribe
    var audio = {
        uri : 'https://nofile.io/f/pDrSFMuSfVh/2f996778-cc3e-496f-a4fb-9e97bb34a040.flac',
    }
    var speechRequest = {
      config: config,
      audio: audio,
    };
    clientSpeech.longRunningRecognize(speechRequest)
        .then(function(transcript) {
            console.log("success transcript",transcript);
        }).catch(err => {
            console.error("transcript error", err);
        });
```
  2. Here is the output : 
```
transcript error { Error: Request contains an invalid argument.
    at C:\wamp\www\video-recorder\node_modules\grpc\src\client.js:554:15 code: 3
, metadata: Metadata { _internal_repr: {} } }
```

When I test with a local file (less than 60 seconds), and using recognize it's working.
NB:  I posted here the audio file in nofile.io where you can download the file, to not include the real location of the file.

Thanks!

**Comment by mlumbroso** [comment]
I think I got the origin of the issue (although the error message is super vague...) 
uri parameter only accepts  Google Cloud Storage URLs : 
1) Why such a limitation ?
2) Any plan to support external storage in the short-term ?
3) That means that for now, if an audio file is longer than 1 minute, there is no way to process it at all if not hosted on GS ?

One good thing would be to have the detail of all parameters in the reference page : https://cloud.google.com/nodejs/docs/reference/speech/0.11.x/v1.SpeechClient

Thanks !

**Comment by stephenplusplus** [comment]
Regarding the docs, there's an issue with the template. It's not showing any options that our methods allow (issue opened here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783)

For the other questions, I can't answer those, unfortunately. We're just a slim wrapper around the API. You can find members of that team through the recommended channels on [the Support page](https://cloud.google.com/speech/support).

However, it does seem that we could accept a `uri` and download it for you, then pass it as a data blob to the API. I'm not sure that will solve many cases, though, as we're still limited by the 1 minute rule.

@alexander-fenster what do you think?

**Comment by stephenplusplus** [comment]
We should probably not do any special handling of a `uri` before the upstream API does. In theory, if we can do it here, they can do it, too. And the fact that they're not is probably telling enough to stay back from implementing ourselves.

If anyone disagrees, or sees another way we can improve, let me know.

**Comment by AlexanderKozhevin** [comment]
Never mind.  Just found anwer in the docs

**Comment by shamoons** [comment]
@AlexanderKozhevin what was the answer? I tried to return the promise, but no dice..

**Comment by AlexanderKozhevin** [comment]
@shamoons Response contains only metadata - name: 618529565046795740
It's an id which you have to use to request final result. 
Like
```
https://speech.googleapis.com/v1/operations/${ID?key=your_google_api_key
```
