### ISSUE TITLE
How to use configuration options?

### ISSUE THREAD

**Issue by ephemer** [googleapis/nodejs-speech#240]
Probably related to #63.

It'd be great to get more documentation on how to use all the configuration options listed e.g. here: https://cloud.google.com/nodejs/docs/reference/speech/2.1.x/google.cloud.speech.v1p1beta1?authuser=1#.RecordingDeviceType

I have tried many things to try to access the options to no avail. My current attempt looks like this:

```
const {
    InteractionType,
    RecordingDeviceType,
    MicrophoneDistance,
    OriginalMediaType,
} = require('@google-cloud/speech');

// ...

const config = {
    sampleRateHertz: sampleRateHertz,
    languageCode: languageCode,
    enableWordTimeOffsets: true,
    enableWordConfidence: true,
    enableAutomaticPunctuation: true,
    speechContexts: [{
        phrases: [
            // strings
        ]
    }],
    metadata: {
        interactionType: InteractionType.VOICEMAIL,
        industryNaicsCodeOfAudio: 611610, // https://www.naics.com/naics-code-description/?code=611610
        recordingDeviceType: RecordingDeviceType.OTHER_INDOOR_DEVICE,
        microphoneDistance: MicrophoneDistance.NEARFIELD,
        originalMediaType: OriginalMediaType.AUDIO,
        originalMimeType: 'audio/m4a',
        audioTopic: // a string
    }
};
```

But these StaticProperties don't seem to be defined anywhere accessible. I managed to find them here https://github.com/googleapis/nodejs-speech/blob/master/src/v1/doc/google/cloud/speech/v1/doc_cloud_speech.js but it's unclear how to import them and whether that'd be a good idea.

Can somebody help me out with this? Thanks

**Comment by kinwa91** [comment]
According to [this sample code](https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.v1p1beta1.js#L53), you should be able to just provide the `string` version of these enum types like so:

```
metadata: {
  interactionType: "VOICEMAIL",
  originalMediaType: "AUDIO",
  ..
}
```

Hope this resolves your issue. Please reopen and let us know if you run into other issues!
