### ISSUE TITLE
Windows10 problem. Cannot run `node recognize.js listen`

### ISSUE THREAD

**Issue by GTamara** [googleapis/nodejs-speech#255]
Hello
I am trying to launch nodejs-speech/samples by using `node recognize.js listen`
but it is not working. The error message is the following:

```sh
node recognize.js listen
Listening, press Ctrl+C to stop.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I am using Windows10, I set `$env:GOOGLE_APPLICATION_CREDENTIALS="D:\projects\current\speech\speech-recognition-1eec10025372.json".`

Also I added sox folder to $path.

When I try another command:
```
node recognize.js sync ./resources/audio.raw -e LINEAR16 -r 16000
```

It works fine.
What is wrong? Let me know, please.

Best regards.

**Comment by JustinBeckwith** [comment]
👋  @googleapis/ml-apis

**Comment by nnegrey** [comment]
Hi, do you have `sox` installed on your machine?

**Comment by jzhao8** [comment]
Does not work, Sox 14.4.2 and 14.4.1 both tried and, yes they were added to PATH.

**Comment by sduskis** [comment]
@ajaaym can you please have someone take a look at this?

**Comment by ajaaym** [comment]
@sduskis ack, will have someone to start on this soon.

**Comment by laljikanjareeya** [comment]
please go through [this](https://github.com/gillesdemey/node-record-lpcm16/issues/8) issue and change the **index.js** of **node-record-lpcm16** as suggested [here](https://github.com/gillesdemey/node-record-lpcm16/issues/8#issuecomment-459752623).

**Comment by bcoe** [comment]
@GTamara just following up, did @laljikanjareeya's recommendation do the trick for you?

**Comment by StillOnMyWay** [comment]
Also following up, any movements toward a longer term fix?

**Comment by laljikanjareeya** [comment]
issue in `node-record-lpcm16` and PR for this issue is already in `node-record-lpcm16` repository, once they release the new version we will upgrade it.

**Comment by bcoe** [comment]
currently blocked by https://github.com/gillesdemey/node-record-lpcm16/pull/46
