### ISSUE TITLE
npm install Error

### ISSUE THREAD

**Issue by julien-c** [googleapis/nodejs-speech#26]
I get an error when trying to npm install (tried the last two released versions of `@google-cloud/speech`):

```
verbose stack Error: ENOENT: no such file or directory, 
rename '/[...]/node_modules/@google-cloud/speech/node_modules/grpc/node_modules/abbrev' 
->
 '/[...]/node_modules/@google-cloud/speech/node_modules/grpc/node_modules/.abbrev.DELETE'
```

Other libs requiring grpc install and work fine.

**Comment by stephenplusplus** [comment]
Thanks for reporting. Could you fill in the issue template? https://raw.githubusercontent.com/googleapis/nodejs-speech/master/.github/ISSUE_TEMPLATE.md

**Comment by stephenplusplus** [comment]
I'm going to close, as we can't reproduce locally or in CI. Please let me know if this is still an issue.
