### ISSUE TITLE
Google cloud speech streaming samples stops

### ISSUE THREAD

**Issue by bramhechatejas** [googleapis/nodejs-speech#267]
The sample provided for Google cloud speech streaming does not help. I have followed every single step. It stops running soon as I start program. So far I know, this issue has been listed down everywhere including stackoverflow but has got no response that can solve this problem. Please take a look at snap I'm sharing. 

![capture1](https://user-images.githubusercontent.com/20275369/50469405-419b7500-09d2-11e9-9dc6-98ce52ed478a.PNG)

**Comment by nnegrey** [comment]
It appears we may have 2 streaming microphone samples. Both are working for me. 

1. https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js#L381-L434
` node recognize.js listen`
2. https://github.com/googleapis/nodejs-speech/blob/master/samples/MicrophoneStream.js
`node MicrophoneStream.js micStreamRecognize`

Which sample are you using?

**Comment by bramhechatejas** [comment]
I have used microphonestream.js. I tried debugging this code, but it's not receiving device options I guess & so it stops soon as it starts. I've installed sox & following is the code snippet, I'm trying to run. 

```
function microphoneStream(encoding, sampleRateHertz, languageCode) {
    // [START micStreamRecognize]

    // Node-Record-lpcm16
    const record = require('node-record-lpcm16');

    // Imports the Google Cloud client library
    const speech = require('@google-cloud/speech');

    const config = {
        encoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
    };

    const request = {
        config,
        interimResults: false, //Get interim results from stream
    };

    const client = new speech.SpeechClient();

    // Create a recognize stream
    const recognizeStream = client
        .streamingRecognize(request)
        .on('error', console.error)
        .on('data', data =>
            process.stdout.write(
                data.results[0] && data.results[0].alternatives[0] ?
                `Transcription: ${data.results[0].alternatives[0].transcript}\n` :
                `\n\nReached transcription time limit, press Ctrl+C\n`
            )
        );

    // Start recording and send the microphone input to the Speech API
    record
        .start({
            sampleRateHertz: sampleRateHertz,
            channels: 1,
            threshold: 0.5, //silence threshold
            verbose: true,
            recordProgram: 'sox', // Try also "arecord" or "sox"
            silence: '10.0', //seconds of silence before ending
        })
        .on('error', console.error)
        .pipe(recognizeStream);

    console.log('Listening, press Ctrl+C to stop.');
    // [END micStreamRecognize]
}

microphoneStream('LINEAR16', 16000, 'en-US');
```

**Comment by nnegrey** [comment]
Ah, that looks like a modified version of the code sample. 

Try the latest version of this sample: https://github.com/googleapis/nodejs-speech/blob/master/samples/MicrophoneStream.js
Run: `node recognize.js listen`

For the code you copied in, I was able to make it work by switching this line:
`recordProgram: 'sox', // Try also "arecord" or "sox"`
to:
```
recordProgram: 'rec', // Try also "arecord" or "sox"
```

**Comment by JustinBeckwith** [comment]
I think the missing information here is likely Windows :) . @bramhechatejas you are running Windows right?  What version?

**Comment by bramhechatejas** [comment]
Yes @JustinBeckwith I'm using windows 10.

**Comment by nnegrey** [comment]
I don't have a Windows machine at the moment, but I'll try to track one down and follow up.

**Comment by bramhechatejas** [comment]
@nnegrey Have you checked this?

**Comment by maheshmahadevan** [comment]
Hi, Running into same issue for Windows 10 , any update will be helpful

**Comment by bomzj** [comment]
The issue seems is related to `node-record-lpcm16` module, which starts and finishes immediately while running `sox -t waveaudio -d mytest.wav` in command prompt capture microphone input and saves in file.
Also, please note that Google has outdated code samples that use `node-record-lpcm16` API calls like `sampleRateHertz` parameter (the correct one is `sampleRate`).

**Comment by Naor1Levi** [comment]
having the exact problem! 
what should i do? @bomzj

**Comment by laljikanjareeya** [comment]
looks issue in `node-record-lpcm16`, if anyone is getting below error than please change the **index.js** of **node-record-lpcm16** as suggested [here](https://github.com/gillesdemey/node-record-lpcm16/issues/8#issuecomment-459752623).
```
Error: spawn rec ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
PR for this issue is already in `node-record-lpcm16` repository, once they release new version we will upgrade it.

**Comment by bcoe** [comment]
I believe this issue might be related to https://github.com/gillesdemey/node-record-lpcm16/pull/46
