### ISSUE TITLE
Malordered Data Received even if the config is sent before

### ISSUE THREAD

**Issue by danajeremy** [googleapis/nodejs-speech#269]
I'm trying to use the Google Speech-To-Text API (through the *@google-cloud/speech* npm package) to transcribe some audio from a browser mic (need to be cross-browser so I can't use the Chrome API).

I'm creating a `streamingRecognize` with the needed parameters and then I push some data to this stream but the API response is the following one: "Malordered Data Received. Send exactly one config, followed by audio data".

Here's the code: 

    const gcpClient = new gcpSpeech.SpeechClient();
    
    const encoding = 'LINEAR16';
    const sampleRateHertz = 16000;
    const languageCode = 'en-US';
    
    const request = {
      config: {
        encoding: encoding,
        sampleRateHertz: sampleRateHertz,
        languageCode: languageCode,
      },
      interimResults: true
    };
    
    const recognizeStream = gcpClient.streamingRecognize(request);
    
    recognizeStream
    .on('data', (data) => {
        console.log("onDataThing", data);
        process.stdout.write(
                  data.results[0] && data.results[0].alternatives[0]
                    ? `Transcription: ${data.results[0].alternatives[0].transcript}\n`
                    : `\n\nReached transcription time limit, press Ctrl+C\n`
                )
    })
    .on('error', (error) => {
        console.log("error", error);
    });
    
    io.on('connection', (socket) => {
        socket.on('audiodata', (data) => { 
            console.log("audiodata", data);
            recognizeStream.write(data);
        });
    });

As you can see, I'm getting the audio from the browser and send it via a socket (using socket.io) to the backend to have a streaming recognition.

The config is sent when creating the stream with `streamingRecognize` and then the audio is sent by chunk of data so I don't understand why is it considered as Malordered.

If you have any idea or solution, that would be awesome!

**Comment by eduardosanzb** [comment]
@danajeremy did you solved this problem?

**Comment by vlobanov** [comment]
For me the issue was happening because in the browser I've been requesting data from `MediaRecorder` and then listening for `dataavailable` etc. Apparently because it's OGG encoded the speech API doesn't understand chunks (even though I passed encoding).

 After I switched to requesting data without MediaRecorder, it started working (with encoding = 'LINEAR16'):

```
function convertFloat32ToInt16(buffer) {
    let l = buffer.length;
    let buf = new Int16Array(l / 3);

    while (l--) {
      if (l % 3 === 0) {
        buf[l / 3] = buffer[l] * 0xFFFF;
      }
    }
    return buf.buffer
  }

  const socket = io("http://localhost:3000");

  function microphoneProcess(e) {
    var left = e.inputBuffer.getChannelData(0);
    var left16 = convertFloat32ToInt16(left);
    socket.emit('audioMessage', left16);
  }

  const handleSuccess = function(stream) {
    const context = new AudioContext();
    const source = context.createMediaStreamSource(stream);
    const processor = context.createScriptProcessor(2048, 1, 1);

    source.connect(processor);
    processor.connect(context.destination);

    processor.onaudioprocess = function(e) {
      microphoneProcess(e);
    };
  };
  navigator.mediaDevices.getUserMedia({audio: {sampleRate: 16000}}).then(handleSuccess);
```
