### ISSUE TITLE
Issue template has 404 links

### ISSUE THREAD

**Issue by talkingnews** [googleapis/nodejs-speech#28]
Both of the links below in the template are broken - can't find suitable alternatives

  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2802.
