### ISSUE TITLE
Guidelines for best practice - number of streamingRecognize requests per client?

### ISSUE THREAD

**Issue by kidplug** [googleapis/nodejs-speech#284]
Is there any practical limit or best practice for using a single SpeechClient instance with many streamingRecognize requests running simultaneously?

Does the SpeechClient maintain a single underlying HTTP2 connection?  Or does it spawn multiple connections once the number of HTTP2 channels/streams reaches a certain number?  

Should I consider using multiple SpeechClients if I wanted to run 100 simultaneous streamingRecognize requests?

**Comment by julien-c** [comment]
Interested in this as well. By the way you'll hit the (default) request limit quota if you get to 100 simultaneous streaming requests: https://cloud.google.com/speech-to-text/quotas#request_limits

**Comment by kidplug** [comment]
How do you figure? 
I see request limit of:
` Processing per 60 seconds | 6,480 seconds of audio `

**Comment by nnegrey** [comment]
@bcoe maybe you know more?
But my understanding is that assuming you don't hit the max set by the server, then the client library should handle all this for you.

**Comment by bcoe** [comment]
@murgatroid99 knows best; but if I recall past conversations, the same underlying connection will be used if accessing the same resource; Michael please correct me if I'm wrong.

**Comment by murgatroid99** [comment]
Yes, in most cases the gRPC client will use a single connection when making multiple requests to a single server. It is possible that the front end server will reject streams if too many streams are open simultaneously on a single connection. The gRPC library does not currently do anything about that; higher-level retry logic may or may not help with that problem.

**Comment by nnegrey** [comment]
@murgatroid99, would it be best then to open a new client for all streaming requests?

**Comment by chiangky** [comment]
I have the same question too, 
I want to call streamingRecognize concurrently, is it the only way to open the new client to proceed the second request (While the first request is still running) ?

**Comment by DevJhns** [comment]
@nnegrey Hi! Have you tried it? I have same problem, tried running two streams on one speech client and tried creating two speech clients for both streams, in any case worked weired, like gcp had one buffer and all audio was messing up

**Comment by zxzzxxzx** [comment]
any progress with the issue? for example what if we start some speech recognition service in 2 different browser tabs simultaniously (using socket.io for communication with node.js server). Now, as it was said, it is not working well...

**Comment by lolz0r** [comment]
I am also seeing an issue when running multiple streams at once.
