### ISSUE TITLE
Speech diarization samples test failure 

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-speech#299]
The samples test is failing on `master` - https://source.cloud.google.com/results/invocations/3e6b3ad8-adb4-4343-b3fe-eb343deb15d0/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-speech%2Fnode8%2Fsamples-test/log

@nirupa-kumar would you mind taking a look? Thanks!

**Comment by JustinBeckwith** [comment]
cc @googleapis/ml-apis @beccasaurus

**Comment by nirupa-kumar** [comment]
Looking into this: The diarization tests don't seem to be failing any more -https://source.cloud.google.com/results/invocations/2eb689a4-8102-4f28-80b0-0a573c55e479/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-speech%2Fnode8%2Fsamples-test/log
Will raise a bug if I see this happening consistently. Please let me know if it would be good to go ahead and close this for now.
