### ISSUE TITLE
progressPercent is always 0

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-speech#307]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2803

<a href="/Maqsim"><img src="https://avatars2.githubusercontent.com/u/1107049?s=88&v=4" height=44 width=44 align=left></a>@Maqsim<br>February 24, 2018 9:57 AM

#### Environment details

  - OS: macOS 10.12.6
  - Node.js version: 8.9.3
  - npm version: 5.6.0
  - google-cloud-node version: 1.1.0

#### Steps to reproduce

  1. require `@google-cloud/speech`
  2. Set config:
```
const transcriptionRequestParams = {
    encoding: 'LINEAR16',
    profanityFilter: false,
    sampleRateHertz: 16000,
    enableWordTimeOffsets: true
  };
```
  3. Upload file into bucket and run `longRunningRecognize`:
```
return uploadToBucket(filePath)
    .then(bucketFile => launchAsyncRecognition(bucketFile, transcriptionRequestParams))
    .then(handleTranscriptions);

function launchAsyncRecognition(bucketFile, config) {
  const audio = { uri: googleBucketLink + '/' + bucketFile.name };
  const request = { config, audio };

  return speechClient.longRunningRecognize(request);
}
```
  4. Inside `handleTranscriptions` add `.on` for `progress`:
``` 
  const operation = data[0];

  operation.on('progress', function (metadata, apiResponse) {
    console.log(metadata);
  });
```
  5. Console log is:
```
{ progressPercent: 0,
  startTime:
   { seconds: Long { low: 1519465382, high: 0, unsigned: false },
     nanos: 856653000 },
  lastUpdateTime:
   { seconds: Long { low: 1519465383, high: 0, unsigned: false },
     nanos: 354594000 } }
```

Thanks in advance for any help.

**Comment by Maqsim** [comment]
Guys, thanks all for any effort.

Unfortunately I don't work on that project anymore and can't check the status of the issue.

**Comment by JustinBeckwith** [comment]
Loud and clear.  If you run into this again - please do let us know!

**Comment by p4rse** [comment]
I am running into the same issue but this time `progressPercent` is missing from the metadata.

#### Environment details

  - OS: macOS 10.14.3
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/speech` version: 3.2.5

#### Steps to reproduce

1. import `@google-cloud/speech``
2. Create a client and set request options:
```javascript
const client = new gcSpeech.SpeechClient();
const request = {
	config: {
		encoding: 'LINEAR16',
		sampleRateHertz: 16000,
		languageCode: 'en-US',
		enableWordTimeOffsets: true,
	},
	audio: {
		uri: gcsUri // 10mins audio file
	}
};
```
3. Make request:
```javascript
client
  .longRunningRecognize(request)
  .then(responses => {
    const [operation, initialApiResponse] = responses;

    operation.on("progress", (metadata, apiResponse) => {
      console.log("> New progress:");
      console.log(metadata);
      console.log("--------------------------------------");
    });

    operation.on("complete", (result, metadata, finalApiResponse) => {
      console.log("> Operation is done!");
    });

    operation.on("error", err => {
      throw err;
    });
  })
  .catch(err => {
    console.error(err);
  });
```

4. Output:
```javascript
> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832569, high: 0, unsigned: false },
     nanos: 472717000 } }

--------------------------------------

> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832570, high: 0, unsigned: false },
     nanos: 874924000 } }

--------------------------------------

> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832571, high: 0, unsigned: false },
     nanos: 761816000 } }

--------------------------------------

> Operation is done!
```

**Note 1:** The first 3 logs from `progress` event were logged immediately after few milliseconds, then it took some time to log `> Operation is done!`

**Note 2:** I used a 10mins audio file for this operation.

**Comment by JustinBeckwith** [comment]
Greetings!  Could we ask you to open a new issue with these details?  It's just easier to keep track that way 😉

**Comment by p4rse** [comment]
> Greetings! Could we ask you to open a new issue with these details? It's just easier to keep track that way 😉

Hi Justin, already done https://github.com/googleapis/nodejs-speech/issues/420

Thank you

**Comment by alexander-fenster** [comment]
Reopening and then closing for accounting reasons
