### ISSUE TITLE
client.recognize returning empty results array

### ISSUE THREAD

**Issue by eitanalka** [googleapis/nodejs-speech#309]
I'm currently having problems trying to get the Node.js client for speech recognition working. When I upload the audio file to https://cloud.google.com/speech-to-text/ , I get the audio transcribed perfectly. However, when I use the Node.js client to do the same thing, I get an empty results array. I used the same configuration as the speech-to-text demo. The only thing that is different is that the audio content bytes are different on the demo site and in my Node file. You can view the content that is getting sent on the demo site by going to the network tab in the Google Chrome Dev Tools. You can view the content that is getting sent in my Node file by uncommenting `console.log(audioBytes);` and redirecting the output of the program to another file. This problem could also be due to some project setting I need to enable. However, I didn't find anything else I need to do besides what's listed in the documentation here: https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries. Please let me know if you need anymore details. Thank you!

#### Environment details

  - OS: macOS 10.14.3 
  - Node.js version: v10.15.1
  - npm version: 6.4.1
  - `@google-cloud/speech` version: 2.3.0

#### Steps to reproduce

  1. Download the audio file I'm trying to recognize: https://drive.google.com/uc?export=download&id=1vJvp2DmDHQMrA1vgEY5kRBKzK7fiIY6y
  2. Create a file with following code in the same directory as audio file:
```js
// Imports the Google Cloud client library
const speech = require('@google-cloud/speech');
const fs = require('fs');

async function main() {
  // Creates a client
  const client = new speech.SpeechClient();

  // The name of the audio file to transcribe
  const fileName = 'audio-sample.wav';

  // Reads a local audio file and converts it to base64
  const file = fs.readFileSync(fileName);
  const audioBytes = file.toString('base64');
  // Uncomment the next line to view contents of audioBytes
  // console.log(audioBytes);
  // The audio file's encoding, sample rate in hertz, and BCP-47 language code
  const audio = {
    content: audioBytes,
  };
  const config = {
    encoding: 'LINEAR16',
    sampleRateHertz: 44100,
    languageCode: 'en-US',
    model: 'default',
  };
  const request = {
    audio,
    config,
  };

  // Detects speech in the audio file
  const [response] = await client.recognize(request);
  console.log(response);
  const transcription = response.results
    .map(result => result.alternatives[0].transcript)
    .join('\n');
  console.log(`Transcription: ${transcription}`);
}
main().catch(console.error);
```
3. Run file. Should return:
```
{ results: [] }
Transcription: 
```

**Comment by yusuf987** [comment]
I have also the same problem,
have you find any solution ???

**Comment by yusuf987** [comment]
ok i found the solution i was using the .amr file 
with below config 
```
  const config = {
      encoding: 'LINEAR16',
      sampleRateHertz: 16000,
      languageCode: 'en-US',
    };
```
which was wrong the correct config for .amr file should look like below 

```
    const config = {
      encoding: 'AMR',
      sampleRateHertz: 8000,
      languageCode: 'en-US',
    };
```
