### ISSUE TITLE
The samples tests are flaking

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-speech#318]
See the sample test results here:
https://source.cloud.google.com/results/invocations/a512f6b7-49ce-4b79-8360-01f4e5186297/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-speech%2Fnode10%2Fsamples-test/log

```
  23 passing (2m)
  1 failing
  1) BetaFeatures
       should run speech diarization on a local file:
     AssertionError: expected 'Transcription: I\'m here\n hi I\'d like to buy a Chrome Cast and I was wondering whether you could help me with that\n Hulu which color would you like we have blue black and breath\n let\'s get the black one\n okay Chris would you like the New Concord Ultra model or the regular Comcast\n regular Chrome Cast design\n okay sure would you like to ship it regular or Express\n Express please\n terrific it\'s on the way thank you very much thank you\n bye\nSpeaker Diarization:\n word: bye, speakerTag: 0' to match /speakerTag: 1/
      at Context.it (system-test/betaFeatures.test.js:41:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by callmehiphop** [comment]
I'm wondering if this was just upstream flakiness, I haven't been able to trigger the same error yet.

**Comment by callmehiphop** [comment]
Need some help from the API team, but it looks like this is just flakiness on their end and not anything to do with the client and/or the samples. I think we either have to just deal with it or change our [assertions](https://github.com/googleapis/nodejs-speech/blob/master/samples/system-test/betaFeatures.test.js#L42) to not care what the value of speak tag is, just that it is present.

**Comment by JustinBeckwith** [comment]
I reached out to @beccasaurus over email, who should be able to point us in the right direction :)

**Comment by beccasaurus** [comment]
The Beta Speech diarization feature is not guaranteed to detect 2 speakers, sometimes only 1 speaker is detected.

**Comment by callmehiphop** [comment]
@beccasaurus oh man I'm a little late now, but whenever we see the failure we actually don't get speaker 1, but rather speaker 0. This threw me off because the upstream docs say it should be a 1-based index.

**Comment by klaaz0r** [comment]
I agree with @callmehiphop the way failing diarization is now handled is not ideal, getting a small set of results with tag 0 is not really useful.
