### ISSUE TITLE
Cannot connect to speech api from aws lambda

### ISSUE THREAD

**Issue by swapnildubal** [googleapis/nodejs-speech#328]
Hi,

I am trying to use the google speech api to transcribe few audio files. 
I am hitting the speech api from a AWS lambda function, but facing below error:

"Auth error:FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: socket hang up"
Same tried from node rest api, it works.

I am using:
Node 8.10
google-cloud/speech: 2.3.0

Please let me know if I need to have some kind of auth settings anywhere.

Thanks

**Comment by bcoe** [comment]
:wave: hi @swapnildubal, how were you configuring authentication for the REST API (I would expect that the same credentials would work). Here's an approach you can take:

1. add `google-auth-library` as a dependency to your project.
2. create a new instance of the auth library, configuring from environment variables you set in your lambda, [see](https://github.com/googleapis/google-auth-library-nodejs#loading-credentials-from-environment-variables).
3. pass the auth client you've created as the `auth` parameter when creating the `@google-cloud/storage` library.

Let me know if this does the trick for you :+1:

**Comment by bcoe** [comment]
@swapnildubal my colleague @callmehiphop points out you shouldn't even need to pull in the `google-auth-dependency`, and should instead be able to set a `credentials` key when initializing your client:

```
client = new speech.SpeechClient({credentials: credentialsObject})
```

:point_up: this credentials object would be populated from environment variables you set in your lambda.

**Comment by sgreenberg** [comment]
@swapnildubal - We're closing this out since it's an old issue but feel free to reopen if it's still causing you problems.
