### ISSUE TITLE
Is the example in "Performing streaming speech recognition on an audio stream" for local use only?

### ISSUE THREAD

**Issue by dshukertjr** [googleapis/nodejs-speech#331]
I am confused about this example:

https://cloud.google.com/speech-to-text/docs/streaming-recognize#performing_streaming_speech_recognition_on_an_audio_stream

How can I take this and create a let's say web app? Why is it node.js, but contains text like "Listening, press Ctrl+C to stop.", which makes it look like it could be used in a web app? 

I guess my question is, is it possible to directly call google speech to text api from a web app without having my server? The example I provided seems to be doing that, but how would my service account be secured if make it a web app?

**Comment by bcoe** [comment]
@dshukertjr the sample in context potentially clarifies a bit:

https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js#L381

The sample code assumes you are running the application from command line, and uses the library `node-record-lpcm16` to record from the mic and pipe it to the speech API.

To build a web application you would need to:

1. create a server that records an audio stream on the front-end:
  * https://www.html5rocks.com/en/tutorials/getusermedia/intro/
2. create a web-server, probably using a something like [express](https://www.npmjs.com/package/express), which accepts the audio stream and in turn streams it to the speech API.

You might also look at the auto-generated REST version of the speech API:

https://www.npmjs.com/package/googleapis

This library does expose a version of the speech API that should function in a front-end context.

**Comment by dshukertjr** [comment]
Thank you for the clarification!
