### ISSUE TITLE
gax fix v0.26 - when will it hit cloudspeech ?

### ISSUE THREAD

**Issue by kidplug** [googleapis/nodejs-speech#343]
It looks like fixes were made in
https://github.com/googleapis/gax-nodejs/issues/403
for:
Bad credentials (or missing) throws UnhandledPromiseRejectionWarning

And the cloudspeech changelog for 2.31 says:
Bug Fixes
fix: throw on invalid credentials (#302)

But the cloudspeech npm 2.3.1 package is still referencing gax v0.25.0

and I still get UnhandledPromiseRejectionWarning when supplying bad creds
for new SpeechClient();

I see on master branch the gax is updated to v0.26.0.
Is a release coming soon that will include this?

**Comment by callmehiphop** [comment]
@bcoe do we have a timeline for upgrading to gax 1.0? All I know is that it should happen soonish?

**Comment by JustinBeckwith** [comment]
Should be this week.  We're following the schedule here:
https://github.com/googleapis/google-cloud-node/issues/2925

Lots of churny PRs to land first :/

**Comment by JustinBeckwith** [comment]
This has landed 🥂 Please do let us know if you're still running into any issues.

**Comment by kidplug** [comment]
So which release do we need to upgrade to?

We are currently:     "@google-cloud/speech": "^2.2.0",

**Comment by JustinBeckwith** [comment]
The latest version, `3.2.0`, has support 🦏
