### ISSUE TITLE
Can I use this package in react-native mobile app ?

### ISSUE THREAD

**Issue by nileshprajapati007444** [googleapis/nodejs-speech#367]
I am creating voice chat app in react-native. I want to translate speech to text using google.

Can I use this package in react-native ? Is it supported ?

Please explain me in detail.

Thanks in advance.

**Comment by JustinBeckwith** [comment]
Greetings!  What have you tried?

**Comment by nileshprajapati007444** [comment]
@JustinBeckwith 

I have tried with below steps:

(1) I have create new project in react-native with below command:
   react-native init  GoogleDemoApp

(2) Then install this package with below command:
  npm install @google-cloud/speech --save

(3) import this package:

// In react-native latest version, below syntax to import package
import speech from '@google-cloud/speech';

// Above import syntax gives error, so i have tried to import as per this package documentation.
const speech = require('@google-cloud/speech');

(4) Run react-native app:
react-native run-android

Issue is that every time I am facing error, and not able to run sample app. 

error: bundling failed: Error: Unable to resolve module `path` from `/GoogleDemoApp/App.js`: Module `path` does not exist in the Haste module map

Let me know if you still any question from myside to understand my issue.

**Comment by bcoe** [comment]
@nileshprajapati007444 as it stands today, you cannot run `nodejs-speech` in react-native or other front-end application (although it's bundled for different mobile clients, I believe react-native ultimately executes JavaScript in what's essentially a browser environment).

_One of the main issues, is that the `http2` dependency that `nodejs-speech` relies on is not available in non-Node.js environments._

What I would recommend would be to run a thin web-server, using a technology like [express](http://expressjs.com/), which executes `nodejs-speech. Your `react-native` application would then make an HTTP request using a module [like node-fetch](https://www.npmjs.com/package/node-fetch)

**Comment by sgreenberg** [comment]
@nileshprajapati007444 and @callmehiphop  - I'm closing out this issue since the feature request feels like it's well covered in https://github.com/googleapis/google-cloud-node/issues/2933. Let me know if that seems wrong.

**Comment by mbifulco** [comment]
@bcoe - does your comment above hold true for `create-react-app`, as well?

full context: I'm trying to create an electron app that uses this api to process audio recorded locally. I've wrapped create-react-app in electron, but can't seem to get the `nodejs-speech` client to authenticate without crashing things.

code: 

```es6
// read credentials from an environment variable
const keysEnvVar = process.env.REACT_APP_GOOGLE_CREDENTIALS;
// parse those credentials as JSON (have verified that this is working correctly)
const credentialKeys = JSON.parse(keysEnvVar);

// app crashes on this line
const client = new speech.SpeechClient({ credentials: credentialKeys });
```
The error trace shows the following (keys/IDs redacted):
<img width="753" alt="Pasted_Image_1_30_20__8_40_PM" src="https://user-images.githubusercontent.com/1844496/73505674-2c490500-43a1-11ea-82bc-0b94d35e991c.png">
