### ISSUE TITLE
Possibility to close stream manually

### ISSUE THREAD

**Issue by marcelgoya** [googleapis/nodejs-speech#37]
Hi folks,

I am using the streamingRecognize function to live stream audio. Is there any way to close the connection with the SDK? I've searched the docs and the code and couldn't find anything.

Cheers

**Comment by stephenplusplus** [comment]
It should work like a normal stream, so just calling `end()` should close the stream and the underlying connection. Let me know if this doesn't work!

**Comment by marcelgoya** [comment]
Works like a charm, thanks a lot! :)
