### ISSUE TITLE
Disturbing "Quota exceeded" error message when no global GCP credentials

### ISSUE THREAD

**Issue by sebght** [googleapis/nodejs-speech#370]
Hi,
I was stuck facing a strange (at first) error message when testing out the basic [quickstart sample](https://github.com/googleapis/nodejs-speech/blob/master/samples/quickstart.js), reporting that the project quota limit had been reached.
Error message :
```
ERROR: { Error: Quota exceeded for quota metric 'speech.googleapis.com/default_requests' and limit 'DefaultRequestsPerMinutePerProject' of service 'speech.googleapis.com' for consumer 'project_number:764086051850'.
    at Http2CallStream.call.on (/Users/macOSuser/Projects/nodejs-speech/samples/node_modules/@grpc/grpc-js/build/src/client.js:102:45)
    at Http2CallStream.emit (events.js:198:15)
    at Http2CallStream.endCall (/Users/macOSuser/Projects/nodejs-speech/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:74:18)
    at /Users/macOSuser/Projects/nodejs-speech/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:163:18
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
 After some (small) investigation, I found that it was needed to setup `GOOGLE_APPLICATION_CREDENTIALS`, even if I had run `gcloud auth application-default login` and setup the correct project.

I know the [quickstart guide](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries) was refering to this correct procedure. However, I found this error message weird and misleading, and that's why I wanted to report it to you.
Feel free to close the issue if you think I am wrong.

#### Environment details

  - OS: macOS Mojave 10.14.5
  - Node.js version: v11.14.0
  - npm version: 6.7.0
  - `@google-cloud/speech` version: 3.1.0

#### Steps to reproduce

  1. Follow the [quickstart guide](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries), except step 2 with the environment variable
  2. This should be it

**Comment by bcoe** [comment]
@sebght did this happen your first time using the API? There is a free tier I believe which should allow for up to 60 minutes of processing. I'm wondering if there's a chance you hit this threshold (the error for missing credentials should be different).

**Comment by sebght** [comment]
hey @bcoe this happened on my second time using the API. I tried it using the CLI and this was ok, but I only used 30s or 1 min of my free tier, so I can't believe this was due to this 60 min quota.

Plus I am not facing this error anymore, since I have set up `GOOGLE_APPLICATION_CREDENTIALS`

**Comment by bcoe** [comment]
@sebght I wonder if the issue might be that a request without `GOOGLE_APPLICATION_CREDENTIALS` ends up hitting a default account that has its time saturated.

_any ways_, It sounds like you're unblocked 👍 and we already have the setting of `GOOGLE_APPLICATION_CREDENTIALS` documented in README.md.

I'm going to go ahead and close this, but will be keeping an eye open for similar issues.
