### ISSUE TITLE
Error: RecognitionAudio not set.

### ISSUE THREAD

**Issue by Messilimeng** [googleapis/nodejs-speech#375]
the file has been save but always say Error: RecognitionAudio not set.

![image](https://user-images.githubusercontent.com/12272166/58926865-37e71c00-877f-11e9-8f1b-18d90c87d031.png)

![image](https://user-images.githubusercontent.com/12272166/58926897-4af9ec00-877f-11e9-9d8e-a1af2712666c.png)

**Comment by Messilimeng** [comment]
code

const Koa = require('koa');
const Router = require('koa-router');
const koaBody = require('koa-body');
const app = new Koa();
const router = new Router();

const fs = require('fs');
const path = require('path')
const port = 5017;
const speech = require('@google-cloud/speech');
const util = require('util');
const exec = util.promisify(require('child_process').exec);

app.use(koaBody({
    multipart: true,
    formidable: {
        maxFileSize: 200 * 1024 * 1024
    }
}));


app.use(async (ctx, next) => {
    console.log(`Process ${ctx.request.method} ${ctx.request.url}...`);
    await next();
});

router.get('/', async (ctx) => {
    ctx.response.type = 'text/html';
    ctx.body = 'this is speech api'
})
router.post('/speech', async (ctx) => {

    const file = ctx.request.files.file;
    let filePath = path.join(__dirname, 'resources') + `/${file.name}`;
    let filePath1 = path.join(__dirname, '') + `/${file.name}`;

    await readStreamFile(file.path,filePath);
   // await readStreamFile(file.path,filePath1);
    const fileread = fs.readFileSync('./resources/'+file.name);
    const audioBytes = await fileread.toString('base64');
    console.log(audioBytes)
    const audio = {
        content: audioBytes,
    };
    const config = {
        encoding: 'LINEAR16',
        ampleRateHertz: 16000,
        languageCode: 'en-US',
    };
    const request = {
        audio: audio,
        config: config,
    };
    let output;
    try {
        const client = new speech.SpeechClient();
        var response = await client.recognize(request)
        const transcription = response[0].results
            .map(result => result.alternatives[0].transcript)
            .join('\n');
        console.log(`Transcription: ${transcription}`);
        console.log(response)
     
        if(transcription!=undefined || transcription!=""){
            let transcription_UP = transcription.replace(new RegExp(" ","gm"),"_").toUpperCase();
            console.log(transcription_UP)
            let cmd ="curl -F 'file=@"+filePath+"' '13.125.147.73:5010/decode?MODE=en&"+transcription_UP+"'"
            console.log(cmd)
            const { stdout, stderr } = await exec(cmd);
            output = stdout
            console.log(stdout)
            console.log(stderr)
        }
        ctx.response.type = 'text/html';
        ctx.body = {
            code: 0,
            words: transcription,
            output:output
        }
    } catch (error) {
        console.log(error)
        ctx.response.type = 'text/html';
        ctx.body = {
            code: 1000,
            date: 'service error',
            output:output
        }
    }


})

const readStreamFile = (frompath,topath) => {
    return new Promise((executor, reject) => {
      let chunks = [];
      const reader = fs.createReadStream(frompath)
      reader.on('data', (chunk) => {
        chunks.push(chunk);
      })
      reader.on('end', () => {
        reader.close();
        executor(reader.pipe(fs.createWriteStream(topath)));
      })
      reader.on('error', (err) => {
        reject(err);
      })
    })
  }
// curl -F file=@"audio.wav" 127.0.0.1:5017/speech

app.use(router.routes());

// 在端口3000监听:
app.listen(port, () => {
    console.log(`app is running port:${port}`)
})

**Comment by bcoe** [comment]
@Messilimeng I see a typo `ampleRateHertz: 16000`, should be `sampleRateHertz: 16000` -- was this a copy paste error, or perhaps this is the underlying issue?

**Comment by Messilimeng** [comment]
@bcoe copy error

**Comment by bcoe** [comment]
@Messilimeng I don't see your `console.log(audioBytes)`, which suggests to me `audioBytes` might be `undefined`, could you add:

```
console.info(`AUDIO BYTES: type = ${typeof audioBytes} ${audioBytes`)
```

**Comment by Messilimeng** [comment]
const file = ctx.request.files.file;
    let filePath = path.join(__dirname, 'resources') + `/${file.name}`;
    let filePath1 = path.join(__dirname, '') + `/${file.name}`;

    const fileread = fs.readFileSync(file );

just read the file path is ok ，but if you first save file then read will have error happen

**Comment by bcoe** [comment]
@Messilimeng the logic in `readStreamFile` looks a little odd, I would probably do something more along the lines of:

```js
const readStreamFile = (frompath,topath) => {
    fs.createReadStream(frompath)
      .pipe(fs.createWriteStream(topath);
    })
```

:point_up: it feels strange to me that you're calling `readstream.close` before performing the pipe. However, the above logic would be a `noop` right? you're just reading from a file and piping to a file.

**Comment by timurmamedov** [comment]
Has anyone managed to fix this issue?. 

We have recently started to get these errors, even though we haven't changed any of the code for like 3-4 months. All packages are up to date as well.

**Comment by malikoum94** [comment]
Hi @timurmamedov we have the same issue, we didn't change the code, but this all request to speech API return this error at the same line as you.

**Comment by Amila17** [comment]
Hi @timurmamedov we are using the .Net SDK and getting the same error as you and haven't changed code for a couple of months now.

**Comment by malikoum94** [comment]
It seems to be fixed now. I think it's an error with google API.

**Comment by timurmamedov** [comment]
Yeah I can confrim too. Works on our side (veed.io) too

**Comment by bcoe** [comment]
@Messilimeng I'm going ahead and closing this, please let me know if the suggestion of modifying your code to:

```
const readStreamFile = (frompath,topath) => {
    fs.createReadStream(frompath)
      .pipe(fs.createWriteStream(topath);
    })
```

did the trick for you :+1:

**Comment by Messilimeng** [comment]
@bcoe hi bcoe after that i change the code then the error is not happened

        const file = ctx.request.files.file;
        let filePath = path.join(__dirname, 'resources') + `/${file.name}`;
        var rs = fs.createReadStream(file.path);
        var ws = fs.createWriteStream(filePath);
        rs.pipe(ws);
        const fileName = './resources/' + file.name
        console.log(fileName)
        const fileread = await fs.readFileSync(file.path);
        const audioBytes = fileread.toString('base64');
        const request = {
            audio: {
                content: audioBytes,
            },
            config: {
                encoding: 'LINEAR16',
                ampleRateHertz: 16000,
                languageCode: 'en-US',
                enableWordConfidence: true,
                enableWordTimeOffsets: true,
            }
        };
