### ISSUE TITLE
when i use socket then how can i save the stream to audio file like .wav

### ISSUE THREAD

**Issue by Messilimeng** [googleapis/nodejs-speech#381]
hello ,i am try to use nodejs socket to  save sream to file then i saved the file but  cant play.waht your help thanks

**Comment by callmehiphop** [comment]
👋 @Messilimeng could you give us some example code of what you've tried?

**Comment by Messilimeng** [comment]
let recognizeStream = this.recognizer.streamingRecognize(request).on("data", (data) => {
            if (this.ready) {
                parseHypothesis(data.results);
                checkForFinal(data.results);
            } else {
                LogUtil.logDebug("v1 recognizer not ready");
            }
        }).on('error', (err) => {
            this.onError(err);
            this.stop();
        }).on('unpipe', () => {
            LogUtil.logDebug("successfully removed pipe stream");
            this.stop();
        });

       bufferStream.pipe(recognizeStream);
        //console.log(sp)
        fs.writeFileSync('../audio/123.wav', bufferStream)

**Comment by Messilimeng** [comment]
@callmehiphop  it is difficult to me ,i just  save the recoginzeStream,lol ,it mast be need other code. i am not good at it, so can you give me some example  code to save the stream to .mav file? thanks

**Comment by bcoe** [comment]
@Messilimeng this looks a little odd, I would do something like what is described here:

https://nodejs.org/en/knowledge/advanced/streams/how-to-use-fs-create-write-stream/

```js
const writeStream = fs.createWriteStream('./output.wav')
writeStream.pipe(bufferStream)
```

If I'm reading your example properly, however, are you trying to both save the file to disk and pass it to the analyzer? To pull this off, I believe you will need to fork the stream. You can find an example of doing this using a PassThrough stream here:

https://gist.github.com/jtbonhomme/842be13d57ad6e852657d88c681755ec

**Comment by Messilimeng** [comment]
thanks lot ,i did it .@boce

**Comment by bcoe** [comment]
@Messilimeng did that example work for you? sounds like we might be able to close this?

**Comment by Messilimeng** [comment]
@bcoe yes the Android should the me the sound is over and save the streambuffer then decode then  stop the socket 
like this
 Buffer.concat([socketBuffer, buffer]);
 let command = 'ffmpeg -i ' + pathname + ' -y -ar 16000 -ac 1 ' + path + Name;

**Comment by bcoe** [comment]
@Messilimeng if you would like to share some of the code as a gist, we can perhaps work some of the methodologies into future code samples.

**Comment by Messilimeng** [comment]
@bcoe my pleasure，when i not busy ，i will send a example code on it.
