### ISSUE TITLE
Which sample to use?

### ISSUE THREAD

**Issue by maragon22** [googleapis/nodejs-speech#384]
Hi, I’m attempting like the demo on cloud.google.com/speech-to-text where I allow the user to transcribe audio from their mic in real time via a website.  I’m just wondering if the code for the demo is available or will the node.js streaming speech example provide the info?  Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the link to the exact sample you're using?  If it's on cloud.google.com, there's a very good chance it's in the `samples` directory here there :)

**Comment by maragon22** [comment]
I’m looking at this example.

https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js

**Comment by nnegrey** [comment]
Ah that code is not owned by us and is not available from what I know. 

The infiniteStreaming or this mic sample is probably the closest thing we have available. 
https://github.com/googleapis/nodejs-speech/blob/master/samples/MicrophoneStream.js
