### ISSUE TITLE
asyncRecognize error

### ISSUE THREAD

**Issue by andrewei88** [googleapis/nodejs-speech#388]
When I run asyncRecognize, I get the error:

```
(node:37047) UnhandledPromiseRejectionWarning: Error: Getting metadata from plugin failed with error: Header field "authorization" must only have a single value
    at Http2CallStream.<anonymous> (/Users/awenwei/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:201:15)
    at Http2CallStream.endCall (/Users/awenwei/node_modules/@grpc/grpc-js/build/src/call-stream.js:63:18)
    at /Users/awenwei/node_modules/@grpc/grpc-js/build/src/call-stream.js:295:18
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:37047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:37047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tried catching the promises, but still get the same error.

**Comment by callmehiphop** [comment]
Interesting, seems to be working fine for me on my local machine. Could you tell us more about your environment, os, Node version, etc.?

**Comment by andrewei88** [comment]
Thanks so much for the response!

My node version is v12.1.0.
My OS is macOS Mojave 10.14.5.
My computer is macbook pro 15 2017
My environment is just vscode using node.

Can you email me at awenwei@google.com instead? Thanks!

**Comment by nnegrey** [comment]
Hi, are you using a specific sample for this or modifying an existing sample to your use case?

**Comment by andrewei88** [comment]
Hi, I'm using a specific sample. I'm using asyncRecognize sample (Not
syncRecognize. synRecognize works for me. I've also tried the python
version of asynchronous recognize and that works for me too). Sample is
found here:
https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js

Thanks!

**Comment by nnegrey** [comment]
Does this command work for you?
`node recognize.js async ./resources/audio.raw -e "LINEAR16" -r 16000 -l "en-US"`

**Comment by andrewei88** [comment]
No, async doesn't work for me. I get the error in the github issue I
opened. Thanks!

**Comment by nnegrey** [comment]
Could you try cloning the repo again, uninstalling and re-installing the client library then?
