### ISSUE TITLE
Requirements but no documentation

### ISSUE THREAD

**Issue by bbookman** [googleapis/nodejs-speech#392]
There are a number of required libraries in nodejs-speech/samples/infiniteStreaming.js,
Yet there is no documentation and one has to either go through the pain of getting a bunch of errors or search through the code for all the requirements.

This is not optimal.
Should one assume the code runs "out of the box"?

**Comment by JustinBeckwith** [comment]
Greetings!  When you run `npm install` in the samples directory, do you get the dependencies you need?

**Comment by bbookman** [comment]
Sorry, I'm new to node.js.  My bad
