### ISSUE TITLE
How do I get a long-running operation name?

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/nodejs-speech#397]
I'm running LongRunningRecognize and I'd like to get the name of the operation.

^--- operation names are used to get/cancel/delete operations

In most languages, Operation has a .name which returns the full name.

I see this in Node.js here: https://googleapis.github.io/gax-nodejs/classes/Operation.html#name

But whenever I try it, the `name` is `undefined`

```js
const [operation] = await client.longRunningRecognize(request);

console.log(`The operation name: ${operation.name}`);
```
```
The operation name: undefined
```

**Comment by beccasaurus** [comment]
@bcoe @JustinBeckwith do y'all happen to know? This isn't Speech-specific but I wasn't sure where to ask. Speech has an LRO so I used it for reproducing.

**Comment by beccasaurus** [comment]
/cc @alexander-fenster incase you know :)

My dumb GAX question

**Comment by beccasaurus** [comment]
If `operation.name` is supposed to be set in this ^ case, should I file as an issue on gax-nodejs?

I can see the path is there somewhere when I print the whole the object

**Comment by alexander-fenster** [comment]
@beccasaurus This is a bug in gax but seems like nobody has ever tried to use those unpopulated fields. Until the bug is fixed, you can get access to the operation name using `operation.latestResponse.name`.

**Comment by beccasaurus** [comment]
Thanks! That works!

Is there an open GAX issue or would you like me to file one? :)

I'm glad this will go into a sample, cause it's a bit of a gotcha -vs- the other languages

**Comment by alexander-fenster** [comment]
I already sent a PR to fix that (linked above ^^^^) :)

**Comment by beccasaurus** [comment]
You are flipping awesome, thank you.

🙏
