### ISSUE TITLE
TypeScript type support

### ISSUE THREAD

**Issue by pbirsinger** [googleapis/nodejs-speech#406]
Would love to have some types. What's ETA for them?

**Comment by JustinBeckwith** [comment]
Greetings!  We're actively working on generating `d.ts` files, but don't have a timeline quite yet.  We'll update this issue as it happens!

**Comment by pbirsinger** [comment]
Ok great - this would be amazing. Thanks!

**Comment by jasonvalenzuela** [comment]
Hey there! Is there any ETA on publishing the `d.ts` files?

**Comment by JustinBeckwith** [comment]
No timeline yet.

**Comment by callmehiphop** [comment]
@JustinBeckwith what are your feelings on hand writing a `d.ts` file here like we did in [Spanner](https://github.com/googleapis/nodejs-spanner/blob/master/src/v1/spanner_client.d.ts)? Usually I wouldn't suggest something like that, but the Speech API is small enough that I don't think it would take a lot of work or run the risk of changing frequently.

**Comment by alexander-fenster** [comment]
Greetings folks,

Types are finally here! Release 3.5.0 (coming out on Monday) will have them.

Fixed by #472.
