### ISSUE TITLE
unbox protobuf Durations for more friendly JS integration

### ISSUE THREAD

**Issue by repentsinner** [googleapis/nodejs-speech#417]
Hi, I've been using `@google-cloud/speech` 3.2.4 v1p1beta1 for the past week or so, and got somewhat stuck trying to make sense of the startTime/endTime Duration objects in the WordInfo objects.

The Javascript-oriented [documentation](https://googleapis.dev/nodejs/speech/latest/google.cloud.speech.v1p1beta1.html#.WordInfo) tapers off around here, pointing to [protobuf pseudocode (?)](https://googleapis.dev/nodejs/speech/latest/google.protobuf.html#.Duration) that doesn't really explain the types involved. Its taken some runtime introspection/errors to realize that `Duration.seconds` and `Duration.nanos` aren't the same type (Long (?) and number, respectively).

I understand somewhat the value of a `Duration` object as it's defined in protobuf to be applicable across many Google apps/services, but the use case within `WordInfo.startTime`/`WordInfo.endTime` appears to be much less demanding (_probably_ don't need 10000 years worth of seconds or nanosecond resolution of mantissa). The only [sample code](https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js#L157) I've found that deals with these seems to bail and just converts everything to strings.

```javascript
      // NOTE: If you have a time offset exceeding 2^32 seconds, use the
      // wordInfo.{x}Time.seconds.high to calculate seconds.
      const startSecs =
        `${wordInfo.startTime.seconds}` +
        `.` +
        wordInfo.startTime.nanos / 100000000;
```

In the spirit of this being a Javascript API, it would be great if (the speech flavor of) the `Duration` object had a `.toNumber()` wrapper that throws an exception if the conversion fails, and prevents us from all having to roll our own error-prone conversions to do any meaningful calculations with these values. At the very least, better information in the speech docs would be helpful to avoid needing to discover at runtime that `.seconds` is a `Long` and how that should be usefully handled in a way that isn't just converting it to a string.

In the short term, can someone on the speech/javascript team confirm if the Long in question is this one? https://github.com/dcodeIO/long.js

Thanks for considering!

**Comment by callmehiphop** [comment]
> In the short term, can someone on the speech/javascript team confirm if the Long in question is this one? https://github.com/dcodeIO/long.js

That is definitely the one!

For a quick workaround, we have a [module](https://github.com/googleapis/nodejs-precise-date) for dealing with [protobuf Timestamps](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Timestamp) which has the same exact format as Durations. In the interim you could probably use this as a workaround until something better presents itself.

```js
const d = new PreciseDate(myDuration);
const ms = d.getTime();
const nanos = d.getFullTime(); // nanos as BigInt
const nanostr = d.getFullTimeString(); // nanos as string
```

**Comment by repentsinner** [comment]
Thanks @callmehiphop! I'll try integrating the PreciseDate module. At first glance I don't see a `.getTime()` method in the docs, and `.getFullTime()` requires BigInt / Node v10+? I need to stay on Node v8 I believe to run in the Firebase Functions environment.

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant so I am closing it. Please reopen if needed.
