### ISSUE TITLE
`progressPercent` is missing from the metadata

### ISSUE THREAD

**Issue by p4rse** [googleapis/nodejs-speech#420]
#### Environment details

  - OS: macOS 10.14.3
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/speech` version: 3.2.5

#### Steps to reproduce

1. import
```javascript
import gcSpeech from '@google-cloud/speech'
```
2. Create a client and set request options:
```javascript
const client = new gcSpeech.SpeechClient();
const request = {
	config: {
		encoding: 'LINEAR16',
		sampleRateHertz: 16000,
		languageCode: 'en-US',
		enableWordTimeOffsets: true,
	},
	audio: {
		uri: gcsUri // 10mins audio file
	}
};
```
3. Make a long running recognize request:
```javascript
client
  .longRunningRecognize(request)
  .then(responses => {
    const [operation, initialApiResponse] = responses;

    operation.on("progress", (metadata, apiResponse) => {
      console.log("> New progress:");
      console.log(metadata);
      console.log("--------------------------------------");
    });

    operation.on("complete", (result, metadata, finalApiResponse) => {
      console.log("> Operation is done!");
    });

    operation.on("error", err => {
      throw err;
    });
  })
  .catch(err => {
    console.error(err);
  });
```

4. Output:
```javascript
> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832569, high: 0, unsigned: false },
     nanos: 472717000 } }

--------------------------------------

> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832570, high: 0, unsigned: false },
     nanos: 874924000 } }

--------------------------------------

> New progress:
LongRunningRecognizeMetadata {
  startTime:
   Timestamp {
     seconds: Long { low: 1565832568, high: 0, unsigned: false },
     nanos: 681584000 },
  lastUpdateTime:
   Timestamp {
     seconds: Long { low: 1565832571, high: 0, unsigned: false },
     nanos: 761816000 } }

--------------------------------------

> Operation is done!
```

**Note 1:** The first 3 logs from `progress` event were logged immediately after few milliseconds, then it took some time to log `> Operation is done!`

**Note 2:** I used a 10mins audio file for this operation.

**Comment by bcoe** [comment]
@p4rse thanks for the bug report :+1:

**Comment by p4rse** [comment]
> @p4rse thanks for the bug report 👍

welcome, any updates about it?

**Comment by p4rse** [comment]
> @bcoe correct me if I'm wrong, but this sounds like a backend issue?

Yep it is!
I tried the same request with REST API with Postman and I got progressPercent missing from metadata in most of times.

**Comment by callmehiphop** [comment]
@beccasaurus any insights here?

**Comment by p4rse** [comment]
Nothing from my side yet!

**Comment by callmehiphop** [comment]
@p4rse since this is a backend issue you might have better luck opening an issue in the [product tracker](https://cloud.google.com/support/docs/issue-trackers).

**Comment by callmehiphop** [comment]
Since there aren't any actionable steps for us to take here, I'm going to close this issue out. Hopefully there's better luck in the product tracker.

**Comment by vin-ni** [comment]
Is there any solution to this?
And how would I implement it with: `const [operation] = await recognitionClient.longRunningRecognize(request);`

**Comment by gabrielstuff** [comment]
hello, 
any one help on this ? 
Pretty lame to not have any solution for progress feedback.

Thanks

**Comment by vin-ni** [comment]
Hello @gabrielstuff ,
unfortunately I'm quite busy on other projects right now, so couldn't find time to rework the library. Probably I'll release a new version some time, but I can't give any information on when right now. 

You're very welcome to do a pull request in the meantime.
