### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Inline audio exceeds duration limit. Please use a GCS URI.

### ISSUE THREAD

**Issue by nitinprajapati1404** [googleapis/nodejs-speech#421]
Hello,

I'm converting speech to text using google speech to text API

it works fine for the short audio file https://cloud.google.com/speech-to-text/docs/sync-recognize

and it works for long audio file using following link https://cloud.google.com/speech-to-text/docs/async-recognize

but as it is paid so is there any other option that we can covert our local file source and use google speech to text API. as when i try to do that get error and suggest me to use GCS.

**Comment by bcoe** [comment]
:wave: @nitinprajapati1404 the documentation indicates that synchronous recognition can be used for samples up to one minute, and for longer than one minute asynchronous recognition must be used.

The code you run for asynchronous recognize should be nearly identical:

https://cloud.google.com/speech-to-text/docs/async-recognize#speech-async-recognize-gcs-nodejs

I believe the pricing is the same per/minute for synchronous vs., asynchronous recognition, both being free until 60 minutes, and then costing money after this:

https://cloud.google.com/speech-to-text/pricing

**Comment by nitinprajapati1404** [comment]
@bcoe  Thanks for the information

but I don't want to use GCS . so is there any way to use speech to text for long audios without gcs?

Thanks

**Comment by bcoe** [comment]
@nitinprajapati1404 yes, here's an example of async recognize being run on a buffer :+1: 

https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js#L174

**Comment by nitinprajapati1404** [comment]
@bcoe I have used the same but still get the suggestion for user GCS

`const config = { 
    encoding: 'MP3',
    sampleRateHertz: 8000,
    languageCode: 'en-US',
  }; 
  // const file = fs.readFileSync(path.join(__dirname,"audios/youtubevideoplayback.mp3"))
  const file = fs.readFileSync(path.join(__dirname,"audios/longvideo.mp3"))
  // const file = fs.readFileSync(path.join(__dirname,"audios/Video.mp3"))
    const audioBytes = file.toString('base64');
    const audio = {
        content: audioBytes,
      };
  
  const request = {
    config: config,
    interimResults: true, 
    audio: audio,
  };

  // Detects speech in the audio file. This creates a recognition job that you
  // can wait for now, or get its result later.
  const [operation] = await client.longRunningRecognize(request);
  
  // Get a Promise representation of the final result of the job
  const [response] = await operation.promise();
  const transcription = response.results
    .map(result => {
      return result.alternatives[0].transcript;
    })
    .join('\n');
  console.log(`Transcription: ${transcription}`);`

**Comment by nitinprajapati1404** [comment]
![image_2019_08_21T05_18_22_939Z](https://user-images.githubusercontent.com/16153250/63404547-46011c00-c401-11e9-9ad1-d5c06145b0f3.png)
@bcoe I have used the same code but still get suggestion for use GCS

**Comment by nitinprajapati1404** [comment]
![image_2019_08_21T05_23_15_895Z](https://user-images.githubusercontent.com/16153250/63404740-05ee6900-c402-11e9-844d-4264cc9f3033.png)
@bcoe  I have used the same code but still get suggestion for use GCS
If I try with short audio then it works but for long video it doesn't.

**Comment by bcoe** [comment]
@nitinprajapati1404 perhaps take a look at streaming recognize:

**Comment by bcoe** [comment]
@nitinprajapati1404 is your clip less than 5 minutes, if so you could use streaming-recognize:

https://cloud.google.com/speech-to-text/docs/streaming-recognize

There's also a tutorial on endless streaming you might read, for longer than 5 minutes:

https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js

**Comment by nitinprajapati1404** [comment]
@bcoe i have already tried it https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js as well.

In this It is automatically take words and return in transcription

I am not able to set my  custom audio in that.

can you pleaase help me out with that? still I try again from my end as well

Thanks for you so much support

**Comment by bcoe** [comment]
@nitinprajapati1404 what audio format are you attempting to stream, out of curiosity, could you potentially use an application to convert it to an MP3 or WAV, before streaming through the API?

**Comment by nitinprajapati1404** [comment]
@bcoe I have used the same example which is given in the infinite streaming js. 

I am just providing you two screenshots one of them where as i have just make one console to see the stream returns the result  and another its outpu

some how I am not able to identify how these transcriptions comes out as i haven't did anything else except keep debug points

I am also not able to get idea of how to use my own audio in this streaming?
1. the transcription output which i have received
![image_2019_08_23T04_55_07_338Z](https://user-images.githubusercontent.com/16153250/63567876-e8033e80-c590-11e9-8f8d-4792726125d2.png)

2. console which i have added in the sample code

![image_2019_08_23T04_54_28_623Z](https://user-images.githubusercontent.com/16153250/63567878-e8033e80-c590-11e9-86ee-d223196e0033.png)

**Comment by dweberlj** [comment]
Hello, in the infinite streaming example (https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js) since I could not get Sox to work correctly on Windows) I stream the audio from a local wav file but I get an error after 1 min of streaming DEADLINE_EXCEEDED.  As per the Google documentation, the streaming API does limit you to 1 minute and I don't see how in the example it handles that 1 min limit.  I'm sure that I am missing something here but any advice would be greatly appreciated.

Here is the modified code in infiniteStreaming.js file to stream from a local wav file instead of a microphone.  It should act identically as they are both streams.

// Start recording and send the microphone input to the Speech API
  // recorder
  //   .record({
  //     sampleRateHertz: sampleRateHertz,
  //     threshold: 0, // Silence threshold
  //     silence: 1000,
  //     keepSilence: true,
  //     recordProgram: 'rec', // Try also "arecord" or "sox"
  //   })
  //   .stream()
  //   .on('error', err => {
  //     console.error('Audio recording error ' + err);
  //   })
  //   .pipe(audioInputStreamTransform);

  fs.createReadStream(process.cwd() + '/sampleaudio.wav').pipe(audioInputStreamTransform);

Thank you.

**Comment by bcoe** [comment]
@dweberlj could I bother you to open a new issue, since I think this is potentially slightly different than @nitinprajapati1404's original problem?

@nitinprajapati1404 with your last example, it looks like you're getting transcription output? What problem are you continuing to run into?

**Comment by nitinprajapati1404** [comment]
Hello ,

I haven't got solution for it.. then i decided to use GCS.
 But it is preferred to use without GCS..

and currently i  am not working on it..

So once i get back to it will think on it else GCS is the solution

**Comment by nitinprajapati1404** [comment]
Hello ,

I haven't got solution for it.. then i decided to use GCS.
 But it is preferred to use without GCS..

and currently i  am not working on it..

So once i get back to it will think on it else GCS is the solution
