### ISSUE TITLE
Issue with speech api

### ISSUE THREAD

**Issue by anjaly** [googleapis/nodejs-speech#451]
Hi team, 

We are using require('@google-cloud/speech').v1p1beta1 to convert our audio file.
But we are getting errors frequently on calling client.recognize().
Below are the errors we are getting.
1. Timeout error
2. Sync input too long. For audio longer than 1 min use LongRunningRecognize with a \'uri\' parameter

In the first case if we try again with the same voice file it will work. 
Can some one pls let us know why it returns timeout error so frequently.

Below are the config we are using.

const config1 = {
                    encoding: 'FLAC',
                    sampleRateHertz: 16000,
                    languageCode: 'en-GB',
                    alternativeLanguageCodes: ['ar-AE', 'ar-SA', 'th-TH'],
                };

**Comment by callmehiphop** [comment]
👋 @anjaly there's been a known issue with grpc that causes users to see an increase in timeouts, I suspect you may be seeing that. Could you verify what version of `@grpc/grpc-js` is installed in your project? 

For an immediate workaround I would suggest trying one of the following

1. Manually updating to `0.6.9`
   ```
   $ npm i @grpc/grpc-js@0.6.9 --save
   ```
1. Using the C++ extension
   ```
   $ npm i grpc --save
   ```

Then you can require the installed package and pass it directly to the speech constructor.

```js
const grpc = require('grpc'); // or @grpc/grpc-js
const client = new speech.SpeechClient({grpc});
```

**Comment by amtdevops** [comment]
Hi @callmehiphop, can u please help me in finding grpc in my code. Below is what we are having in our code now.

 const speech = require('@google-cloud/speech').v1p1beta1;
                const client = new speech.SpeechClient({
                    projectId: config.api.PROECT_ID,
                    keyFilename: config.api.FILENAME
                });
How should we modify this?

**Comment by callmehiphop** [comment]
@amtdevops let me know if the following helps

```js
const grpc = require('grpc');
const speech = require('@google-cloud/speech').v1p1beta1;
const client = new speech.SpeechClient({
  projectId: config.api.PROECT_ID,
  keyFilename: config.api.FILENAME,
  grpc: grpc
});
```

**Comment by meredithslota** [comment]
Checking in -- it seems like this response from @callmehiphop  answered the question, so I'm going to go ahead and close this. Please reopen if needed. Thanks!
