### ISSUE TITLE
Webm as supported format 

### ISSUE THREAD

**Issue by urosran** [googleapis/nodejs-speech#478]
Hi guys thanks for the awesome library! 

Maybe I am doing something wrong but it doesn't seem like you can send a request to the API with webm encoding which seems odd given that default format chrome records in is webm. I'm sure you thought about this so any information would be more than welcome 🙂

Thanks again!

**Comment by b-loved-dreamer** [comment]
Hi @urosran. This issue may no longer be relevant, but I wanted to share some info before closing it. The services does accept ```WEBM_OPUS``` for audio encoding. You can read more about encoding in this [page](https://cloud.google.com/speech-to-text/docs/encoding). Please reopen this issue if you need to.
