### ISSUE TITLE
long running job for firebase functions limited timeout

### ISSUE THREAD

**Issue by dfdgsdfg** [googleapis/nodejs-speech#501]
Firebase functions support only 9mins.

https://cloud.google.com/functions/docs/concepts/exec#timeout

Is there any way to use webhook or gcp pubsub for async long job inside gcp functions?

https://cloud.google.com/community/tutorials/cloud-functions-async

**Comment by matrix4123** [comment]
I ended up creating a small container that essentially replicates a cloud function and deployed it to  Cloud Run. So when I need to translate something I send a request to it and Cloud Run will spin up the container and it can live until the long running translate completes.

You could probably architect some complex solution that sticks the LRO ID into a queue and then use a cloud timer to periodically check the status, but it sounded a bit too complex for the situation.

**Comment by dfdgsdfg** [comment]
Thanks.

At this moment, I use app engine for this job. I hope there's a simpler way. 😄

**Comment by b-loved-dreamer** [comment]
It looks like this question has been answered. I am closing this issue but feel free to reopen.
