### ISSUE TITLE
Networking questions

### ISSUE THREAD

**Issue by jinyeng** [googleapis/nodejs-speech#502]
When using infiniteStreaming example (https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js), what kind of communication happens between client and google cloud ?

For example , when sending file chunks from local machine to google what type of connection is it ? HTTP ? WebSocket ?

Similarly when receiving transcribed text from google what type of communication is it ?

**Comment by b-loved-dreamer** [comment]
Hi @jinyeng. From our docs:

```Streaming Recognition (gRPC only) performs recognition on audio data provided within a gRPC bi-directional stream. Streaming requests are designed for real-time recognition purposes, such as capturing live audio from a microphone. Streaming recognition provides interim results while audio is being captured, allowing result to appear, for example, while a user is still speaking.```

You can read more about it [here](https://cloud.google.com/speech-to-text/docs/basics#speech_requests). Also, check out [gRPC](https://www.grpc.io/docs/what-is-grpc/core-concepts/#bidirectional-streaming-rpc).

I am now closing this issue but feel free to reopen if needed.
