### ISSUE TITLE
is it possilbe to implement on browser and to input from chrome like browser and do live streaming 

### ISSUE THREAD

**Issue by symbol3382** [googleapis/nodejs-speech#506]
Is it possible to implement in browser php for streaming audio from browser

**Comment by stephenplusplus** [comment]
Would you mind elaborating on what you'd like to do?

**Comment by symbol3382** [comment]
I want is to make the speech to text in browser although its possible but with webkit only which binds to chrome users only
Is there any way to make it for all browsers by javascript existing api

**Comment by dimassrio** [comment]
Na, I believe the library available is NodeJS library, REST API only support non streaming option.

**Comment by b-loved-dreamer** [comment]
It looks like this question has already been answered. I am closing this issue.
