### ISSUE TITLE
Getting Undefined result 

### ISSUE THREAD

**Issue by anjanaNewput** [googleapis/nodejs-speech#509]
My code is 

```js 

let wavData = fs.readFileSync('./output.flac');

    wavData.toString('base64');
    console.log(wavData);
    const audio = {
        content: wavData
    };
    
    const config = {
        encoding: 'FLAC',
        //sampleRateHertz: 44100,
        languageCode: 'fr-CA',
        //model: 'default'
        audioChannelCount:1
    };
    const request = {
        audio: audio,
        config: config,
    };
    
    // Detects speech in the audio file
    //console.log(request);
    const response = await client.recognize(request);
    console.log(JSON.stringify(response.results));
    //console.log(client);
    const transcription = response.results
        .map(result => result.alternatives[0].transcript)
        .join('\n');
    console.log(`Transcription: ${transcription}`);
```

I have a Flac audio file and I got result like this 

[ { results: [ [Object] ] }, undefined, undefined ]

when I read results array it will give me undefined. Please let me know whats wrong here.

**Comment by bcoe** [comment]
@anjanaNewput this looks close to our [sample](https://github.com/googleapis/nodejs-speech/blob/master/samples/recognize.js#L25), one thing I notice is that sample rate is commented out, what happens when you specify a sample rate?

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
