### ISSUE TITLE
isFinal results delayed by a minute and returns around 160 words 

### ISSUE THREAD

**Issue by jinyeng** [googleapis/nodejs-speech#514]
For live streams, we are getting lot of sentences in final result all at once. And we get only  one result every minute. This makes result unusable since its so delayed. We do get interim results but we would like to use final results and hoping there was a way to get results in smaller bunch/ grouped sentences.

Here is one example. You can see how much stuff is returned at once every minute. Also included how Amazon returns final transcript in finer chunks every few seconds which allows us to display it with a minimal delay. 

### Google
![image](https://user-images.githubusercontent.com/58823520/73567433-657e8500-4434-11ea-9daa-b0b5016f6ee0.png)

### Amazon
![image](https://user-images.githubusercontent.com/58823520/73567781-1553f280-4435-11ea-967c-9cd7b2220716.png)

We also tried setting singleUtterance to true which doesn't returns result with so much of missing transcript.

**Comment by vishald123** [comment]
Hi @jinyeng, Please refer to the [SelectModel ](https://cloud.google.com/speech-to-text/docs/basics#select-model)and set the sampling rate according to the live stream audio type you are using. I hope you are using [InfiniteStreaming.js](https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js) sample for live streaming.

**Comment by jinyeng** [comment]
Yup, I am using infiniteStreaming. Also have tried every model on the list. Same result. Went through documentation and tried every possible combination of parameters. Nothing makes any difference. I see some people also complaining about the same with web socket example on google group with no response. 

https://groups.google.com/forum/#!topic/cloud-speech-discuss/IkmhQYlqol4

**Comment by vishald123** [comment]
Could you please provide the config and type of Livestream audio input you are using.

**Comment by jinyeng** [comment]
@vishald123 As I mentioned , if you try google's websocket sample you will get same exact issue.

Some one else has mentioned same issue in google group thread when using websocket demo link.
https://www.google.com/intl/en/chrome/demos/speech.html

Here is the result they had.
https://www.loom.com/share/f38ad41c9fb941739e4ad3700327a03c

Problem is final results for live stream/microphone come way later when you talk normally (like podcast). Timing words from interim results is not possible cause timings are just empty. So at this point google speech to text is not much usable in our scenario cause we need to time words from interim results.

**Comment by jinyeng** [comment]
@AVaksman @vishald123 This thread has all the required information. Would appreciate some input.

**Comment by vishald123** [comment]
@jinyeng, I am facing other errors currently but I’m investigating into your issue.

**Comment by sskorol** [comment]
@vishald123 @jinyeng we are also using infinite streams as a baseline for our code. We send audio chunks from FE (React) to BE (NestJS) via websockets, and then stream them to Google via provided streaming API.

What we have noticed is that periodically there's no `isFinal: true` returned in response (even when we completely stop speaking). A stream just stuck on getting interim results. We can talk more and more, but a payload always contains `isFinal: false` when this issue happens.

We implemented a custom pause handling logic based on a final transcribe returned from STT. And as we don't receive it, our algorithm is now broken.

So we can't rely on a final transcribe anymore. And I would agree with @jinyeng that it makes no sense to create workarounds based on interim results. It'll make our logic more complicated and error prone.

**Comment by konsti** [comment]
We experience the exact same issue when transcribing audio from an RTMP stream that was encoded with AAC and was recoded to PCM with FFmpeg. `isFinal` is never sent, even when we stop speaking for several seconds.

When we stream raw audio with OBS for testing purposes `isFinal` responses are sent by Google when we stop speaking.

**Comment by nattapote** [comment]
I am also facing the delay of "`isFinal` = true" with only the **th-TH** languageCode in **quiet** environment. However, en-US is working fine with both **quiet and noisy** environments.

**Comment by jinyeng** [comment]
So as usual seems like google doesn't care about people using their products. More for their own products. I am out, moving on with Amazon's solutions.

**Comment by stephenplusplus** [comment]
I'm sorry for the delay we've taken coming up with a resolution. As it appears now, the upstream API is not providing useful or expected responses. This report would be better handled by that team, as we are just the wrapper around their logic as the Node.js client library.

There are some useful links here for this type of issue: https://cloud.google.com/speech-to-text/docs/getting-support. Google engineers monitor the questions on StackOverflow, as well as the Google and Slack group mentioned on that page.

Let me know if you think this is an issue we can resolve from the client library and I will re-open this issue. If anyone else should find a solution or more clarity on these issues, please let the rest of us know.

Sorry again for the trouble and the time you've spent on the issue.
