### ISSUE TITLE
npm install @google-cloud/speech fails

### ISSUE THREAD

**Issue by ea167** [googleapis/nodejs-speech#519]
Due to the dependency to protobufjs:

```
> protobufjs@6.8.8 postinstall /root/my-project/node_modules/protobufjs
> node scripts/postinstall

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/root/my-project/node_modules/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protobufjs@6.8.8 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protobufjs@6.8.8 postinstall script.
```

I have found some forum stating that 
`npm install --unsafe-perm` worked, but this is bad for security and should not be needed!

My NodeJs is installed under `/opt/node/`

Very disappointing as a first experience with Google Speech...

#### Environment details

  - OS: Linux CentOS 7.7
  - Node.js version: 12.14.1
  - npm version: 6.13.4
  - `@google-cloud/speech` version: 3.5.4

#### Steps to reproduce

  1. npm install @google-cloud/speech

**Comment by bcoe** [comment]
@ea167 you should not need to run `npm install --unsafe-perm`, are you perhaps performing the install as a `sudo` user?

1. make sure that your local Node.js installation has appropriate permissions, i.e., you don't need to be `sudo` to run `npm install`. I highly recommend [nvm](https://github.com/nvm-sh/nvm) for installing and managing Node.js.
2. in a fresh directory, e.g., `my-speech-testing`, install:

   ```
   mkdir my-speech-testing
   npm init
   npm i @google-cloud/speech
   ```

This works like a charm for me:

```
bencoe@bencoe:/tmp/my-speech-testing$ npm i @google-cloud/speech
npm WARN tmp@1.0.0 No description
npm WARN tmp@1.0.0 No repository field.

+ @google-cloud/speech@3.5.4
updated 1 package in 6.452s
```

**Comment by ea167** [comment]
Hello @bcoe,

Thank you for your advice and feedback.
I don't `sudo` for the install. I don't use `nvm` for NodeJS, I have a manual install in `/opt/node`.

Out of 43 packages that my project depends upon (and thousands of cascading dependencies), `@google-cloud/speech` &  `protobufjs` are the only ones causing troubles.

This protobufjs issue https://github.com/protobufjs/protobuf.js/issues/877 mentions the same problem, and it may be due to the NodeJS install directory -> some script must be wrong in protobufjs.

I ended up using `--unsafe-perm` for the first install and then it worked. That's bad however.

Hope it helps!

**Comment by bcoe** [comment]
It would appear this is an issue with `protobuf.js` in some environments, and not `@google-cloud/speech` specifically, it might be worth adding a comment there.

It's worth noting that `@google-cloud/speech` installs appropriately without running the protobuf post-install script:

```js
npm i @google-cloud/speech --ignore-scripts
```

So it might be worth investigating why that step is even needed in protobuf.js.

**Comment by bcoe** [comment]
@alexander-fenster @murgatroid99 looking at protobuf.js, I'm not 100% sure what the point of the post install script is, and it seems to occasionally be causing problems for customers. Might be worth investigating whether we could remove this step?

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
