### ISSUE TITLE
Empty words offset for interim results

### ISSUE THREAD

**Issue by jinyeng** [googleapis/nodejs-speech#524]
We do get final results only about every 50 seconds if a speaker is talking continuously. We tried to use interim results, however word offsets are absent in interim results. This makes it really hard to time interim results. And final results are really delayed. Any plan on improvements ?

![image](https://user-images.githubusercontent.com/58823520/73991688-e77e1a80-491a-11ea-84b8-e3e9f0fce486.png)

**Comment by jinyeng** [comment]
Checking if there was any update on this. We are unable to sync results to our HLS stream because offset is empty and final result takes forever to receive.

**Comment by thesofakillers** [comment]
+1 to this issue, improvements here are essential for _accurate_ syncing of real time captions to HLS streams. It almost defeats the purpose of the `streaming` speech-to-text API. Bump

**Comment by stephenplusplus** [comment]
Unfortunately, this sounds like a backend issue, as opposed to our client library. There are a few ways you could reach the relevant team listed on the official Speech support page: https://cloud.google.com/speech-to-text/docs/getting-support. Sorry we can't be of more assistance from here.
