### ISSUE TITLE
How to mock streamingRecognize()

### ISSUE THREAD

**Issue by MayamaTakeshi** [googleapis/nodejs-speech#530]
I'm writing an app that calls speech.SpeechClient().streamingRecognize()
I need to mock the server interaction for this.
Is there anything in the node client that I can use to achieve this?

**Comment by laljikanjareeya** [comment]
Here is one test-case that create mock of `streamingRecognize` you can take reference of it.
https://github.com/googleapis/nodejs-speech/blob/00f1bade4f140b506c765bd68bcfe22b0bbe55e5/test/gapic-speech-v1.ts#L236-L260

**Comment by MayamaTakeshi** [comment]
Got it. Thanks.
