### ISSUE TITLE
Support Quran rules

### ISSUE THREAD

**Issue by MrHazimAli** [googleapis/nodejs-speech#54]
Hye, I would like to know if this package support to record user speak and reading quran, and check whether it's correct or no?

or check whether that user speak and check whether it's the same with text provided in arabic ? 

thank you! :-)

**Comment by stephenplusplus** [comment]
@alexander-fenster ?

**Comment by alexander-fenster** [comment]
Hello @MrHazimAli,

This package is a Node.js client library wrapping [Google Cloud Speech](https://cloud.google.com/speech/) service API. It does not provide any extra functionality, but it makes it easier to call Speech API from your Node.js code. The Speech API allows you to convert the speech provided as an audio file or as a stream to text.

To answer your question, the package will help you recognize what the user said (Arabic is supported, see the full list of languages [here](https://cloud.google.com/speech/docs/languages)). All the logic other than speech recognition is out of scope of this library.

If you scroll down [this page](https://cloud.google.com/speech/) you'll see the 'Start now' button that you can use to test the recognition engine in any language before you start writing any code.

Let me know if it helps!

**Comment by MrHazimAli** [comment]
I see.. alright, thanks! it really help answering my question :-) I guess I need to build the logic itself

btw, thanks @alexander-fenster for answering this question!
