### ISSUE TITLE
How to set up price plan in code?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [googleapis/nodejs-speech#545]
In docs it's said that there are 4 options for pricing. 
How to set up the chippest one?

<img width="777" alt="Screenshot 2020-03-01 at 01 21 56" src="https://user-images.githubusercontent.com/4464561/75615925-2dfe1800-5b5b-11ea-8c61-b3f52dd19bb0.png">

**Comment by b-loved-dreamer** [comment]
Hi @AlexanderKozhevin, [Here](https://cloud.google.com/speech-to-text/pricing) are the latest details on the Speech-To-Text service. By opting in to data logging, you can benefit from lower Speech-to-Text pricing. [Here's](https://cloud.google.com/speech-to-text/docs/enable-data-logging) how you can opt in to data logging. This would be a cheaper option relative to wether you're using Enhanced models or not. 

I will go ahead and close this issue. If you have any more concerns, please don't hesitate to reopen this issue or open a new one.
