### ISSUE TITLE
Speech API speechContexts not recognising arrays

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-speech#56]
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2813

<a href="/CharlotteGore"><img src="https://avatars2.githubusercontent.com/u/443518?s=88&v=4" height=44 width=44 align=left></a>@CharlotteGore<br>April 4, 2018 11:21 AM

Despite passing an array to speechContext.phrases, I am getting the following error:

```
ERROR: TypeError: .google.cloud.speech.v1.RecognitionConfig.speechContexts: array expected
    at Type.RecognitionConfig$fromObject [as fromObject] (eval at Codegen (/redacted/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:55:9)
    at Type.fromObject (/redacted/node_modules/protobufjs/src/type.js:538:25)
    at Type.LongRunningRecognizeRequest$fromObject [as fromObject] (eval at Codegen (/redacted/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:10:21)
    at Type.fromObject (/redacted/node_modules/protobufjs/src/type.js:538:25)
    at serialize (/redacted/node_modules/grpc/src/protobuf_js_6_common.js:70:23)
    at ServiceClient.Client.makeUnaryRequest (/redacted/node_modules/grpc/src/client.js:544:17)
    at apply (/redacted/node_modules/lodash/lodash.js:499:17)
    at ServiceClient.wrapper (/redacted/node_modules/lodash/lodash.js:5356:16)
    at /redacted/node_modules/@google-cloud/speech/src/v1/speech_client.js:175:39
    at timeoutFunc (/redacted/node_modules/google-gax/lib/api_callable.js:171:12)
```

#### Environment details

  - OS: OSX v10.11.6
  - Node.js version: v8.11.1
  - npm version: 5.6.0
  - google-cloud-node version: 196.0.0

#### Steps to reproduce

Code is here, it's mostly copied straight from the documentation. I have other code generating the real array but I tested it with the simplest possible array for testing and still getting the same result.

```js
const config = {
  enableWordTimeOffsets: true,
  encoding: 'FLAC',
  sampleRateHertz: '16000',
  languageCode: 'en-GB',
  speechContexts: {
    phrases: ['dog', 'cat']
  }
};

const audio = {
  uri: 'gs://bucket/audio.flac'
};

const request = {
  config,
  audio,
};

client
  .longRunningRecognize(request)
  .then(data => {
    const operation = data[0];
    // Get a Promise representation of the final result of the job
    return operation.promise();
  })
  .then(data => {
    const response = data[0];
    console.log(`${JSON.stringify(response, null, 2)}`);
  })
  .catch(err => {
    console.error('ERROR:', err);
  });
```

**Comment by stephenplusplus** [comment]
Just to confirm, what version of `@google-cloud/speech` are you using?

**Comment by CharlotteGore** [comment]
It's version 1.4.0, installed it today from NPM, it's whatever's tagged as latest I believe.

**Comment by picklesrus** [comment]
I just ran into this too. But solved it by making speechContexts an array. i.e.

`speechContexts: [{
    phrases: ['dog', 'cat']
  }]
 `
instead of
`speechContexts: {
    phrases: ['dog', 'cat']
  }
 `
I think the [phrase hints documentation](https://cloud.google.com/speech-to-text/docs/basics#phrase-hints) is missing the extra [].  Once I changed it to an array it seems to be recognizing gibberish words better when I provide them via phrase hints.

**Comment by taegyunum** [comment]
@picklesrus that solved my problem thank you !

**Comment by kinwa91** [comment]
Verified both the [Node.js](https://cloud.google.com/nodejs/docs/reference/speech/2.1.x/google.cloud.speech.v1#.RecognitionConfig) and [Phrase Hints](https://cloud.google.com/speech-to-text/docs/basics#phrase-hints) docs both specify `speechContexts` as an array of object. Marking as fixed.

Please re-open if you run into issues with using Phrase Hints. :)

**Comment by mxrguspxrt** [comment]
Does speechContexts phrases support single words or sentences? What if there is more than 1 different context? Why the speechContexts: [] is an array? Unable to get any value from adding phrases.

**Comment by dave-dm** [comment]
> Verified both the [Node.js](https://cloud.google.com/nodejs/docs/reference/speech/2.1.x/google.cloud.speech.v1#.RecognitionConfig) and [Phrase Hints](https://cloud.google.com/speech-to-text/docs/basics#phrase-hints) docs both specify `speechContexts` as an array of object. Marking as fixed.
> 
> Please re-open if you run into issues with using Phrase Hints. :)

On this page it documents:

```

SpeechContext

JSON representation
--
{   "phrases": [     string   ] }


```
https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig#speechcontext
