### ISSUE TITLE
Transcription is blank and no error for mp3 in sample code

### ISSUE THREAD

**Issue by weilies** [googleapis/nodejs-speech#581]
Greeting, i have follow the [sample code](https://github.com/googleapis/nodejs-speech#using-the-client-library) but only change the video source to MP3 and the config as below

> const config = {
>         enableAutomaticPunctuation: true,
>         encoding: 'LINEAR16',
>         languageCode: 'en-US',
>         model: 'default',
>         sampleRateHertz: 16000,
>     };

May i know what's the correct setup to transcript a MP3 file? another concern, if i am collecting audio source from public, there could be different file extension (mp3, wav, raw), with different sample rate, how could the API handle all without the developer to define the sample rate, encoding , etc?

Thanks for the guide.

**Comment by vishald123** [comment]
Hey @weilies, You need to set encoding to **MP3** in the config object as follows

```js
const config = {
        enableAutomaticPunctuation: true,
        encoding: 'MP3',
        sampleRateHertz: 16000,
        languageCode: 'en-US',
        model: 'default',
    };
```

**Comment by dariushazimi** [comment]
@weilies did you resolve your issue?

**Comment by dariushazimi** [comment]
Keep in mind
**FLAC or LINEAR16 is recommended**.". Here: https://cloud.google.com/speech-to-text/docs/best-practices

Using mp3, mp4, m4a, mu-law, a-law or other lossy codecs during recording or transmission may reduce accuracy. If your audio is already in an encoding not supported by the API, transcode it to lossless FLAC or LINEAR16. If your application must use a lossy codec to conserve bandwidth, we recommend the AMR_WB, OGG_OPUS or SPEEX_WITH_HEADER_BYTE codecs, in that preferred order.

You can always convert your audio from mp3, mp4, etc to flac before you start the transcription.

**Comment by weilies** [comment]
I think is my source clip that having issue. For my context, i have different mp3 client and some are quite accurate.

**Comment by zijing07** [comment]
Hi, I am using `"@google-cloud/speech": "^4.10.0"`, but in the generated `protos.d.ts`, there is no `MP3` option:

```
                namespace RecognitionConfig {

                    /** AudioEncoding enum. */
                    enum AudioEncoding {
                        ENCODING_UNSPECIFIED = 0,
                        LINEAR16 = 1,
                        FLAC = 2,
                        MULAW = 3,
                        AMR = 4,
                        AMR_WB = 5,
                        OGG_OPUS = 6,
                        SPEEX_WITH_HEADER_BYTE = 7,
                        WEBM_OPUS = 9
                    }
                }
```

@dariushazimi Can you help with this issue?

**Comment by zijing07** [comment]
> Hi, I am using `"@google-cloud/speech": "^4.10.0"`, but in the generated `protos.d.ts`, there is no `MP3` option:
> 
> ```
>                 namespace RecognitionConfig {
> 
>                     /** AudioEncoding enum. */
>                     enum AudioEncoding {
>                         ENCODING_UNSPECIFIED = 0,
>                         LINEAR16 = 1,
>                         FLAC = 2,
>                         MULAW = 3,
>                         AMR = 4,
>                         AMR_WB = 5,
>                         OGG_OPUS = 6,
>                         SPEEX_WITH_HEADER_BYTE = 7,
>                         WEBM_OPUS = 9
>                     }
>                 }
> ```
> 
> @dariushazimi Can you help with this issue?

Nvm, I found the way to use the `v1p1beta1`, which supports `MP3`.

```
const {v1p1beta1, protos} = require('@google-cloud/speech');
```
