### ISSUE TITLE
How to get progress information from LongRunningRecognize Operation

### ISSUE THREAD

**Issue by gabrielstuff** [googleapis/nodejs-speech#586]
hello nodejs Google Speech Team ! 

Thanks for all the work accomplished to abstract the communication with the speech API. Your works make working with the API fairly easy.

Regarding following issues : 
- https://github.com/googleapis/nodejs-speech/issues/420
- https://github.com/googleapis/nodejs-speech/issues/34
- https://github.com/googleapis/nodejs-speech/issues/307

and a number of SO questioning about how to get the `progress` of a `LongRunningRecognize`, I've finnaly decided to post.

We are using a simple `const [operation] = await speechclient.longRunningRecognize({...})`

The whole code is the example in the documentation.

The response from the `progress` event does not contain information except when the jog is done. It goes at `100` which at least is ok.

The `progress` event only triggers two or three times.

Trying to get more information with the `getOperation` method, does not give more information.

So how one could get a clear progress state of the operation ?

Thanks for any feedback or help that would allow to get it.

#### Environment details

  - OS: `macOS`
  - Node.js version: `v10.16.1`
  - npm version: `6.14.4`
  - `@google-cloud/speech` version: `3.6.0`

#### Steps to reproduce

  1. Copy the example : https://cloud.google.com/speech-to-text/docs/async-recognize#speech_transcribe_async_gcs-nodejs
  2. Add the code : 

```
operation.on('progress', (metadata, apiResponse) => {
        console.log('> New progress:')
        console.log(metadata)
})
```
   3. Observe that you do not get `progressPercent` key

Regarding where the code reference `progressPercent` we can find it here https://github.com/googleapis/nodejs-speech/blob/v3.6.0/protos/protos.json#L856

I might try to use the curl method to check the operation data regarding the doc : https://cloud.google.com/speech-to-text/docs/async-recognize#speech_transcribe_async_gcs-protocol

Did not have the time so far.

Thanks a lot !

**Comment by stephenplusplus** [comment]
I believe those other issues show there isn't anything we can do about it, as the backend controls the progress updates we receive. There was a recommendation to file the issue with the appropriate team on their issue tracker: https://cloud.google.com/support/docs/issue-trackers

Am I mistaken? Is there something we can do from this library?

**Comment by gabrielstuff** [comment]
Well the google team looks like they just don't give a *** : https://issuetracker.google.com/issues/73046873 the issue has been opened in 2018. It looks like an eternal bug. Progress is certainly hard to estimate, but for sure a necessary feature for our user to be happy!

**Comment by stephenplusplus** [comment]
@JustinBeckwith Is there a way to follow up on this issue? It's assigned, but ironically, we can't see it's progress :) https://issuetracker.google.com/issues/73046873

**Comment by gabrielstuff** [comment]
Thanks. Just saw your message few weeks ago. Hope someone in the AI & Machine Learning team will feel concerned.

**Comment by sgreenberg** [comment]
Hi folks - I'm on the Cloud AI Developer Relations engineering team here at Google. I talked with the Cloud AI engineers. They note that intermediate results are, unfortunately, not guaranteed. This can happen with short files and sometimes even for long files. We intend to give intermediate progress, but it may not be possible in every scenario. The behavior you're seeing is the one the product has intended to deliver. I hope that's helpful information. I'm sorry if it makes it more difficult to use in your situation.

**Comment by gabrielstuff** [comment]
Hi Steven,

Thanks for the feedback which clarify a lot the behaviour. So basically, we will never get the progress. Thanks.

One question nonetheless, do you plan to integrate an estimate of the progress as an enhancement ?

Thanks a lot.

**Comment by nover** [comment]
I stumbled upon this issue from a web-search on how to get the percent progress reporting. 

So here's how I solved it (in javascript):

```javascript
/**
* Small util that allows you to `await sleep(ms_to_sleep)`
*/
function sleep(ms) {
    return new Promise(resolve => {
        setTimeout(resolve, ms);
    })
}

/**
 * Poll long running speech transcribe progress
 * @param client {SpeechClient}
 * @param operationName {string} Name of the operation to poll on
 * @return {Promise<void>} Resolves once the progress reports "done"
 */
async function pollOperationProgress(client, operationName) {
    let doContinue = true;
    do {
        const response = await client.checkLongRunningRecognizeProgress(operationName);
        const {
            latestResponse,

            /**
             * @type LongRunningRecognizeMetadata
             */
            metadata
        } = response;

        console.log(`Transcribe progress: ${metadata.progressPercent.valueOf()}`);

        // if we aren't done, well, we should continue polling
        doContinue = !latestResponse.done;
        // give the google api a break and wait for 10 seconds before polling again
        await sleep(10 * 1000);

    } while (doContinue);
}

async function waitForOperationAndDoStuff(operation) {
    const [response] = await operation.promise();
    // TODO do stuff with the `response`
}

/**
* Method stub where the client is initialized and the speech recognition process is started
*/
async main() {
    const client = new speech.SpeechClient();
    const request = .... // TODO insert your speech transcribe request / config

    // Fire off the long running recognize
    // start the progress-polling 
    //grab the operation promise and wait for both async operations to complete
    const [operation] = await client.longRunningRecognize(request);
    const transcriber = waitForOperationAndWriteTranscribedContent(operation);
    const polling = pollOperationProgress(client, operation.name);
    
    await Promise.all([polling, transcriber]);
}

```

**Comment by mfissehaye** [comment]
> I stumbled upon this issue from a web-search on how to get the percent progress reporting.
> 
> So here's how I solved it (in javascript):
> 
> ```js
> /**
> * Small util that allows you to `await sleep(ms_to_sleep)`
> */
> function sleep(ms) {
>     return new Promise(resolve => {
>         setTimeout(resolve, ms);
>     })
> }
> 
> /**
>  * Poll long running speech transcribe progress
>  * @param client {SpeechClient}
>  * @param operationName {string} Name of the operation to poll on
>  * @return {Promise<void>} Resolves once the progress reports "done"
>  */
> async function pollOperationProgress(client, operationName) {
>     let doContinue = true;
>     do {
>         const response = await client.checkLongRunningRecognizeProgress(operationName);
>         const {
>             latestResponse,
> 
>             /**
>              * @type LongRunningRecognizeMetadata
>              */
>             metadata
>         } = response;
> 
>         console.log(`Transcribe progress: ${metadata.progressPercent.valueOf()}`);
> 
>         // if we aren't done, well, we should continue polling
>         doContinue = !latestResponse.done;
>         // give the google api a break and wait for 10 seconds before polling again
>         await sleep(10 * 1000);
> 
>     } while (doContinue);
> }
> 
> async function waitForOperationAndDoStuff(operation) {
>     const [response] = await operation.promise();
>     // TODO do stuff with the `response`
> }
> 
> /**
> * Method stub where the client is initialized and the speech recognition process is started
> */
> async main() {
>     const client = new speech.SpeechClient();
>     const request = .... // TODO insert your speech transcribe request / config
> 
>     // Fire off the long running recognize
>     // start the progress-polling 
>     //grab the operation promise and wait for both async operations to complete
>     const [operation] = await client.longRunningRecognize(request);
>     const transcriber = waitForOperationAndWriteTranscribedContent(operation);
>     const polling = pollOperationProgress(client, operation.name);
>     
>     await Promise.all([polling, transcriber]);
> }
> ```

This is the recommended way according to the document. However it doesn't actually print the percentage value. It's zero all the way until it reaches 100.
