### ISSUE TITLE
end mic stream and restart on click 

### ISSUE THREAD

**Issue by rithiksachdev** [googleapis/nodejs-speech#598]
OS: Ubuntu 18.04
Node js version: 12.16.2
Npm version: 6.14.5
@google-cloud/speech version - 3.6.0
Steps to reproduce - 
index.js - 
```javascript
       function microphoneStream(boolval) {
	
	// Node-Record-lpcm16
	const recorder = require('node-record-lpcm16');
  
	// Imports the Google Cloud client library
	const speech = require('@google-cloud/speech');
  
	const config = {
	  encoding: 'LINEAR16',
	  sampleRateHertz: 16000,
	  languageCode: 'en-US',
	};
  
	const request = {
	  config,
	  interimResults: false, //Get interim results from stream
	};
  
	// Creates a client
	const client = new speech.SpeechClient();
  
	// Create a recognize stream
	const recognizeStream = client
	  .streamingRecognize(request)
	  .on('error', console.error)
	  .on('data', data =>
		process.stdout.write(
		  data.results[0] && data.results[0].alternatives[0]
			? `Transcription: ${data.results[0].alternatives[0].transcript}\n`
			: '\n\nReached transcription time limit, press Ctrl+C\n'
		)
	  )
  
	// Start recording and send the microphone input to the Speech API
	recorder
	  .record({
		sampleRateHertz: 16000,
		threshold: 0, //silence threshold
		recordProgram: 'rec', // Try also "arecord" or "sox"
		silence: '5.0', //seconds of silence before ending
	  })
	  .stream()
	  .on('error', console.error)
	  .pipe(recognizeStream);
	  
	  if(boolval)
	  {
		  console.log("try to turn off")
		  recognizeStream.end();
		  //recognizeStream._destroy()
	  }
	console.log('Listening, press Ctrl+C to stop.');
	// [END micStreamRecognize]
  }
```
**This the microphoneStream function which is called by the following function but is not working**
index.js (contd.)
```javascript
        router.post('/clicked',function(req,res,next){
	console.log('start');
	microphoneStream(boolval)
	if(boolval)
	{
		boolval=false
	}
	else{
		boolval=true
	}
})
```
HTML 
```html
<h3 class="multisteps-form__title">User Account &nbsp;&nbsp;<button type="button" id="mic" class="btn btn-dark"><i style="font-size: x-large;" class="fas fa-microphone-alt"></i></button></h3>
<script src="/js/function.js" type="text/javascript"></script>
```
function.js
```javascript
const btns=document.getElementById('mic');
  btns.addEventListener('click',function(err){
    console.log('button was clicked');

  fetch('/clicked', {method: 'POST'})
    .then(function(response) {
      if(response.ok) {
        console.log('Click was recorded');
        return;
      }
      throw new Error('Request failed.');
    })
    .catch(function(error) {
      console.log(error);
    });
  })
```
ERROR - 
```
NodeError: write after end
    at writeAfterEnd (/home/rithik/Desktop/aaiway/node_modules/pumpify/node_modules/readable-stream/lib/_stream_writable.js:261:12)
    at Pumpify.Writable.write (/home/rithik/Desktop/aaiway/node_modules/pumpify/node_modules/readable-stream/lib/_stream_writable.js:305:21)
    at Socket.ondata (_stream_readable.js:695:22)
    at Socket.emit (events.js:322:22)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```
Question :- How to turn on and off Mic-Stream?

**Comment by stephenplusplus** [comment]
I'm pasting in our issue template. Please make sure to read and complete this so we can help. Also include any error messages you are receiving.

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-speech/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/speech` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vishald123** [comment]
@rithiksachdev, if I am getting it right, you are trying to turn the mic stream ON and OFF from a frontend with a button click.
I am not really a frontend guy but let me know if the following solution works for you.
```
<form action="/clicked" method="post">
            <input type="submit" id="1" name="boolval" value="false">
            <input type="submit" id="1" name="boolval" value="true">
</form>
```
Frontend code for two values

And for the route, you can try as follows

```js
app.post('/clicked', (req, res) => {
    console.log('start');
    let boolval1 = req.body.boolval
    var boolval = (boolval1 == 'true');
    microphoneStream(boolval)
    res.redirect('/')
})
```

Hope that helps!

**Comment by rithiksachdev** [comment]
Thank you @stephenplusplus for your reply, I have updated my issue please have a look. I could not find any documentation for my issue. Thank you @vishald123 for your answer but that doesn't solve the problem because it is giving the same error. There needs to be some change in the index.js file.

**Comment by rithiksachdev** [comment]
Can anyone please tell me how to end a stream and restart it?

**Comment by b-loved-dreamer** [comment]
Hi @rithiksachde, ```CTRL+C``` kills the current process altogether. It does not just end the stream. I want to clarify that to avoid confusion of any sort. You can end the stream by calling ```recognizeStream.destroy();``` on it. T restart it, you need to employ some logic that also "destroys" the ```recorder``` (sets it to null, maybe), rebuilds it and, ```.pipe(recognizeStream);``` again. Here an [example](https://medium.com/@madhura.gore/how-to-get-rid-of-longtime-elapsed-without-audio-and-resource-exhausted-error-in-google-speech-to-a471c47fdec) that accomplish something similar. 

This answer does not provide the specific logic necessary to accomplish this goal, if possible. It does, however, attempt to clarify the goal as stated for the purpose of helping get closer to said goal.

**Comment by b-loved-dreamer** [comment]
Closing. Won't fix (no repro)
