### ISSUE TITLE
Not 'ending' phrase in Spanish language

### ISSUE THREAD

**Issue by kotiko80** [googleapis/nodejs-speech#599]
Hello Team,

It seems that if you select English (en-US), you can speak and your code works correctly.

Example:
If you say "Hello world" (silence) "I'm your father"
Your program output is:

- Hello world

- I'm your father.

But, if you select Spanish language (es-ES), the' phrase' never ends!

Example:
If you say "Hola Mundo" (silence) "Soy tu padre"
Your program out is:

- Hola Mundo yo soy tu padre ...

and all phrases after that are concatenated in Spanish.. the Speech-to-text doesn't 'ends' the phrase.
I have the same problem in my own code... Do you know what could be the cause?

**Comment by stephenplusplus** [comment]
Thanks for reporting, @kotiko80.

@sgreenberg, this sounds like it could be a backend issue, as opposed to in our library code. Do you have any suggestions for how to proceed? Thanks!

**Comment by kotiko80** [comment]
Hi @sgreenberg, 
I put in contact with Google Speech-To-Talk support team. They confirmed the issue and it seems that they will fix it in next 3 business days. Hope so!

**Comment by stephenplusplus** [comment]
@kotiko80 thanks again for bringing this up. I'll close the issue here, as it is being addressed by the backend team. Let me know if there's anything else we can do!
