### ISSUE TITLE
client.recognize doesn't return result nor error

### ISSUE THREAD

**Issue by xavicolomer** [googleapis/nodejs-speech#6]
#### Environment details

  - OS: OSX 10.12.6
  - Node.js version: v4.3.2
  - npm version: 2.14.12
  - @google-cloud/speech version: 0.11.0

#### Steps to reproduce

NOTE: In the example I am using **keyFilePath** but I also tried **export GOOGLE_APPLICATION_CREDENTIALS=/path/to/file**

Code

  ```javascript
const audio = {
            content: base64AudioFileContents,
          };

          const client = new speech.SpeechClient({
            projectId: 'project-id',
            keyFilePath: 'path/to/file.json'
          });

          const config = {
            encoding: 'LINEAR16',
            sampleRateHertz: 16000,
            languageCode: 'en-US',
          };

          const request = {
            audio: audio,
            config: config
          };

          client
            .recognize(request)
            .then(data => {
              console.log(data);
              const response = data[0];
              const transcription = response.results
                .map(result => result.alternatives[0].transcript)
                .join('\n');
              
                console.log(data)
            })
            .catch(err => {
              console.log(error);
            });
```

**Comment by stephenplusplus** [comment]
Sorry for the confusion-- the property name is `keyFilename`. Would you try that real quick?

**Comment by xavicolomer** [comment]
Doesn't seem to work. Not even a TIMEOUT, how can I help / provide more information?

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce using similar snippets, such as running the samples here: https://github.com/googleapis/nodejs-speech/tree/master/samples

Could you provide reproduction steps / put together a small repo I can clone to try to reproduce?

**Comment by xavicolomer** [comment]
I found it.

Must be an absolute path to keyFilename. Relative path won't work.

```javascript
const client = new speech.SpeechClient({
            projectId: 'qbo-nice',
            keyFilename: '/this/must/be/absolute/path/to.json'
          });
```
