### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by gowrisankarvoltuswave** [googleapis/nodejs-speech#60]
Can you guys tell me how to Set up authentication with a service account so you can access the API from your local workstation. i am using dynamic service accounts.. 

I followed this link ---> https://cloud.google.com/docs/authentication/getting-started
Here i am getting list of my project names.. 

When i am trying to detect my intent it say permission denied.. error code 7

I already enabled dialog flow api in my google library and added permissions to service account..

Can any one share source code for authentication.. 

Thanks!

**Comment by stephenplusplus** [comment]
After creating and downloading the JSON service account key file, remember the file path, and provide it as `keyFilename` to the Speech constructor:

```js
const speech = require('@google-cloud/speech');
const client = new speech.SpeechClient({
  keyFilename: '/path/to/keyfile.json'
});
```

Then be sure the Cloud Speech API is enabled on this page: https://console.cloud.google.com/apis/api/speech.googleapis.com/overview

Let me know if you still have issues!
