### ISSUE TITLE
Is duration attribute in <prosody/> ssml not supported? 

### ISSUE THREAD

**Issue by SkyTreasure** [googleapis/nodejs-speech#600]
I went through the documentation of Google Text to Speech SSML. https://developers.google.com/assistant/actions/reference/ssml#prosody

So there is a tag called which as per the documentation of W3 Specification can accept an attribute called duration which is a value in seconds or milliseconds for the desired time to take to read the contained text.

So <speak><prosody duration='6s'>Hello, How are you?</prosody></speak> should take 3 seconds for google text to speech to speak this! But when i try it here https://cloud.google.com/text-to-speech/ , its not working and also I tried it in rest API.

Does google text to speech doesn't take duration attribute into account? If not then is there a way to achieve the same?

**Comment by telpirion** [comment]
This is the repository for Speech-to-Text, not [Text-to-Speech](https://github.com/googleapis/nodejs-text-to-speech).

The current list of supported SSML attributes is [here](https://cloud.google.com/text-to-speech/docs/ssml#prosody).
