### ISSUE TITLE
Getting Empty Result

### ISSUE THREAD

**Issue by gobindabd** [googleapis/nodejs-speech#609]
Getting Empty Result!! From Server Side, I am sending live audio 

**here is my code**  

var cluster = require( "cluster" ); //Require the cluster module
var http = require( "http" ); //Require the http module
var ws = require( "ws" ).Server; //Require the WebSocket server module

//GOOGLE START
const speech = require('@google-cloud/speech');
const client = new speech.SpeechClient({keyFilename: '/usr/local/node_programs/service_account_file.json'});

const encoding = 'MULAW';
const sampleRateHertz = 8000;
const languageCode = 'en-US';
const single_utterance = true;

const config = {
	encoding: encoding,
	sampleRateHertz: sampleRateHertz,
	languageCode: languageCode,
};

const audio = {
	content: null
}

async function main() 
{
	const [response] = await client.recognize({audio: audio,config: config})
	const transcription = response.results
	.map(result => result.alternatives[0].transcript)
	.join('\n');
	console.log(`Transcription: ${transcription}`);
}

//GOOGLE END

var workers = new Array();

if( cluster.isMaster )
{
	var cpus = require( "os" ).cpus().length;
	for( var i = 0; i < cpus; i ++)
	{
		var thread = cluster.fork();
		thread.on("message", function( message )
		{
			workers.forEach( function( worker )
			{
				if( worker.process.pid != message.pid )
				{
					worker.send( message.msg );
				}
			});
		});
		workers.push( thread );
	}
	return;
}

var server = http.createServer().listen( 8080 );
var wss = new ws( {server: server} );

var connections = new Array();

process.on( "message", function( message )
{
	connections.forEach( function( ws ){
	ws.send( message );
	});
});

wss.on( "connection", function( ws ){
	console.log((new Date()) + ' Connection accepted process id'+ process.pid + ' - Protocol Version ' + ws.webSocketVersion);

//ws.send( "Connected to #"+ process.pid );

ws.on( "message", function( message ){

audio.content = message.toString('base64')
console.log(audio.content);

main().catch(console.error);

connections.forEach( function( otherWs ){
if( otherWs != ws ){
otherWs.send( message );
}
});
process.send( {pid: process.pid, msg: message} );
});
ws.on( "close", function(){
var index = connections.indexOf( ws );
connections.splice( index, 1 );
});
connections.push( ws );
});

**Comment by b-loved-dreamer** [comment]
Hi @gobindabd, would you please provide the client-side code you use to feed the audio content to the server/service.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
