### ISSUE TITLE
Show '%' of conversion for long audio file + Email alert upon completion

### ISSUE THREAD

**Issue by weilies** [googleapis/nodejs-speech#610]
My script is currently able to translate audio clip >1min from firebase storage. [Thanks to the sample script from google doc site.](https://cloud.google.com/speech-to-text/docs/async-recognize#transcribing_long_audio_files_using_a_google_cloud_storage_file) My next challenge is, how to provide a more responsive and friendly workflow?

Currently my javascript is run in google cloud shell. How to move the same whole script serve as webpage instead of 'node my-script.js' from cloud shell?
For a 90mins script, could we show a '% of completion' so user could estimate the waiting time?
How to convert the sample code from google, be Promise method, which will trigger email upon completion? And could still send email even user closed the browser?

I just learn Google Speech API about a month, and i know a bit of Angular/Typescript, but i couldn't figure out how to mix both logic together in angular with my concerns above.

Thanks for the helps and support and have a GREAT day!

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant so I am closing it. I suggest you check the latest versions of the library and reopen this issue if your request is not included in it.
