### ISSUE TITLE
Using Firebase Cloud Function with Google API

### ISSUE THREAD

**Issue by weilies** [googleapis/nodejs-speech#613]
I was able to create a simple speech to text node program and trigger via "node <my-program>.js".
But i couldn't convert my node program into Firebase cloud function due to the immature skills.
I also [posted in StackOverflow for help](https://stackoverflow.com/questions/62466063/how-to-trigger-a-gcp-google-speech-api-via-firebase-cloud-function).

Very appreciated for the helps and insights!

**Comment by stephenplusplus** [comment]
I'm glad to see it looks like you've resolved the issue on StackOverflow!
