### ISSUE TITLE
Request to support codec "4-bit IMA ADPCM"

### ISSUE THREAD

**Issue by weilies** [googleapis/nodejs-speech#621]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
i have my program able to transcript WAV (certain codec), MP3, FLAC. But there is one WAV clip i failed. The detail i have [logged to stackoverflow](https://stackoverflow.com/questions/62835631/need-right-codec-for-a-wav-file-in-google-speech-to-text-api) 
This clip can never be transcript unless i manually convert it to other WAV format but the quality of transcription is pretty bad. I am sorry for couldn't share the original clip from authorities.

 **Describe the solution you'd like**
It's an important use case and likely a deal breaker for me. Hopefully google team could address my challneges.

 **Describe alternatives you've considered**
Nope so far.

**Comment by b-loved-dreamer** [comment]
Hi @weilies 

Thank you for submitting this request. I will raise your concern to the appropriate team.

**Comment by b-loved-dreamer** [comment]
Feature request
