### ISSUE TITLE
Streaming wav file doesn't know the sample rate in advance

### ISSUE THREAD

**Issue by ddfridley** [googleapis/nodejs-speech#624]
Going through the example for streaming a wav file,  though speech to text it requires the programer to set the sampleRateHertz in advance.  But different wav files can have different sample rates.  A program would have to read in the wav file before piping to recognizeStream in order to figure out the sampleRateHertz of the wav file - it seems to contradict the idea of using a stream.

The example code should deal with this - show us how to set the sampleRateHertz in the config based on what's in the wav file while using the stream api. 

Or  - I wish the product would figure out the sampleRateHertz based on the incoming wav file - like it does for client.recognize and client.longRunningRecognize

**Comment by munkhuushmgl** [comment]
Are you referring to this sample example ? --> https://github.com/googleapis/nodejs-speech/blob/fbc0caf8115d24b50fc049374bc65eafbe5ef24e/samples/recognize.js#L333

According to our best practices, Sampling rate --> 
If possible, set the sampling rate of the audio source to 16000 Hz. Otherwise, set the sample_rate_hertz to match the native sample rate of the audio source (instead of re-sampling).

**Comment by ddfridley** [comment]
The code I used was at https://cloud.google.com/speech-to-text/docs/streaming-recognize#performing_streaming_speech_recognition_on_an_audio_stream but it seems to be the same as what's referenced above.

My point is, I have a wav file to transcribe.  My perspective is it's already recorded and the use case is to transcribe it.  

The sample_rate_hertz needs to match what's in the wav file and this is example code for a streaming api.   The example should read in the wav file in order to see what the header is, in order to set sample_rate_hertz.  But the example doesn't include that - and it's a bit awkward because you are having to read in the file before streaming - rather than just streaming the file.  I've also learned that you better check the header and make sure it's in mono and not stereo.  I ended up writing code for this, and reporting an issue on the 'product' at https://issuetracker.google.com/issues/161730015  You can see the code I wrote for this there.

I think it would help future developers if these details were added to the example code.

**Comment by munkhuushmgl** [comment]
@ddfridley Thanks for reporting an issue. since there is no ETA, u can keep this issue open until it's closed or close this and get update from your reported issue from bugainzer.

**Comment by b-loved-dreamer** [comment]
This issue jas been closed with Status: Won't Fix (Infeasible) on https://issuetracker.google.com/issues/161730015
