### ISSUE TITLE
Add Enums for configuration of encodings

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-speech#63]
The speech api uses a few different constants in its config. For instance, a user needs to set an encoding. The python version of this does this and it makes encoding discoverability a bit easier. It also avoids magic strings in the code.

I think adding similar support to the nodejs-speech API would be an improvement.

Here is a link to the python code I reference: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/speech/google/cloud/speech_v1p1beta1/gapic/enums.py#L18

**Comment by laljikanjareeya** [comment]
I think this feature has been covered in [this](https://github.com/googleapis/nodejs-speech/pull/472) PR.

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant so I am closing it. You can reopen it if needed.
