### ISSUE TITLE
Empty Transcription in Android audio React Native with Node JS API

### ISSUE THREAD

**Issue by chuksgpfr** [googleapis/nodejs-speech#634]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi.
I'm converting audio record to text with react native and Node js API. When i record on iOS, I get result for .wav file but not for .m4a file for android. this is my config below.

```
const sttConfig = {
            // if you need punctuation set to true
            enableAutomaticPunctuation: true,
            encoding: "LINEAR16",
            // same rate as we use in our ffmpeg options
            sampleRateHertz: 44100,
            languageCode: "en-US",
            //model: "default"
        }
```

I still get empty transcription

**Comment by chuksgpfr** [comment]
@munkhuushmgl please help

**Comment by munkhuushmgl** [comment]
@chuksgpfr we are not officially support react native. However, if you are getting empty transcription in android, you might want to check if the audio bytes are same as ios one.

**Comment by chuksgpfr** [comment]
@munkhuushmgl 

How go i check that ?

This below is for iOS

```
{
  name: '1596797073276.wav',
  data: <Buffer 52 49 46 46 f8 27 04 00 57 41 56 45 4a 55 4e 4b 1c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 66 6d ... 272334 more bytes>,
  size: 272384,
  encoding: '7bit',
  tempFilePath: '',
  truncated: false,
  mimetype: 'audio/vnd.wave',
  md5: '36bd0da8475e27d2e3ac3da89e4ea6e8',
  mv: [Function: mv]
}
Transcription:  Hello. Hello. Hello hello hello hello. Hello.
```

And this is for android
```
{
  name: '1596797097643.m4a',
  data: <Buffer 00 00 00 18 66 74 79 70 6d 70 34 32 00 00 00 00 69 73 6f 6d 6d 70 34 32 00 00 bd ce 6d 64 61 74 21 11 45 00 14 50 01 46 ff f1 0a 5a 5a 5a 5a 5a 5a 5a ... 49812 more bytes>,
  size: 49862,
  encoding: '7bit',
  tempFilePath: '',
  truncated: false,
  mimetype: 'audio/m4a',
  md5: '566754e90c1a94a0e09b63e94e1729f0',
  mv: [Function: mv]
}
Transcription: 
```

**Comment by munkhuushmgl** [comment]
@chuksgpfr There must be dependency or library which convert data (from (google-nodejs-speech) ) into these values you got. You may want to investigate there. I think you should contact with React native community or support team. We are here help on nodejs-speech related issues, not react native development.

With that note, I am closing this issue.
