### ISSUE TITLE
run `node quickstart.js`, did not receive response and the process exist. 

### ISSUE THREAD

**Issue by maoyaru** [googleapis/nodejs-speech#637]
#### Environment details

  - OS:
  - Node.js version: v12.16.3
  - npm version:
  - `@google-cloud/speech` version: ^4.1.1

#### Steps to reproduce

  1. follow the README.md and run `node quickstart.js`, a few minites later, the process exits without any response information consoled.

also, i console something before and after `const [response] = await client.recognize(request);`, the information before `const [response] = await client.recognize(request);` consoled successfully but  the information after didn't.

**Comment by maoyaru** [comment]
Is the reason related to my being in China？

**Comment by maoyaru** [comment]
anyone can help?

**Comment by maoyaru** [comment]
my code:
`// Imports the Google Cloud client library
const speech = require('@google-cloud/speech');
const fs = require('fs');

async function main() {
  // Creates a client
  const client = new speech.SpeechClient();

  // The name of the audio file to transcribe
  const fileName = './brooklyn.flac';

  // Reads a local audio file and converts it to base64
  const file = fs.readFileSync(fileName);
  const audioBytes = file.toString('base64');

  // The audio file's encoding, sample rate in hertz, and BCP-47 language code
  const audio = {
    content: audioBytes,
  };
  const config = {
    languageCode: "en-US",
    sampleRateHertz: 16000,
    encoding: 'FLAC',
    audioChannelCount: 1
  };
  const request = {
    audio: audio,
    config: config,
  };
  console.log('client')
  // Detects speech in the audio file
  const [response] = await client.recognize(request);
  const transcription = response.results
    .map(result => result.alternatives[0].transcript)
    .join('\n');
  console.log(`Transcription: ${transcription}`);
}
main().catch(console.error);`

and result:

![image](https://user-images.githubusercontent.com/55369838/90382129-eb041280-e0b0-11ea-8304-1d8458e5daa6.png)

**Comment by munkhuushmgl** [comment]
@maoyaru I will look into it, right now.

**Comment by munkhuushmgl** [comment]
> Is the reason related to my being in China？

No, we don't discriminate against anyone. In fact, there is no info about GEO location in your github.

**Comment by munkhuushmgl** [comment]
![image](https://user-images.githubusercontent.com/45373284/90821434-c180fc00-e2e7-11ea-8d11-248f665fff02.png)
I was able to run successfully without any problem using your code snippet.

**Comment by munkhuushmgl** [comment]
which directory are you running quickstart.js ? also make sure you are reading the file.
If you are not reading audio file, that is most likely to give you no response.

I had to tweak your on line 9 and ran it from samples directory.
```
    const fileName = './resources/brooklyn.flac';
```

**Comment by telpirion** [comment]
> > Is the reason related to my being in China？
> 
> No, we don't discriminate against anyone. In fact, there is no info about GEO location in your github.

Hello!  I'm not aware of any restrictions that should prevent you from using the Speech-to-Text API.

One option: you might try running this sample in [Cloud Shell](https://cloud.google.com/shell/docs).

**Comment by maoyaru** [comment]
> > > Is the reason related to my being in China？
> > 
> > 
> > No, we don't discriminate against anyone. In fact, there is no info about GEO location in your github.
> 
> Hello! I'm not aware of any restrictions that should prevent you from using the Speech-to-Text API.
> 
> One option: you might try running this sample in [Cloud Shell](https://cloud.google.com/shell/docs).

so It seems that there is no problem with my code, but still i can't run it successfully. so upset. still thanks so much for your sincere help! and i'll  share you all the reason if i find it. thank you again!

**Comment by maoyaru** [comment]
> which directory are you running quickstart.js ? also make sure you are reading the file.
> If you are not reading audio file, that is most likely to give you no response.
> 
> I had to tweak your on line 9 and ran it from samples directory.
> 
> ```
>     const fileName = './resources/brooklyn.flac';
> ```

useful info, thank you

**Comment by dariushazimi** [comment]
@maoyaru 

The sample code runs fine. See the image below. 
Have you exported your credentials as per docs?
Do you have the credentials.js file in the right folder?

![image](https://user-images.githubusercontent.com/622048/91479909-2f8d6c00-e870-11ea-9048-eb3319de2f3b.png)
