### ISSUE TITLE
Add the possibility to trigger 'isFinal' or make the silence threshold configurable 

### ISSUE THREAD

**Issue by MadyAkira** [googleapis/nodejs-speech#638]
I would like to trigger manually the 'isFinal' response from google. 

I need to recognize a list of words like this, said pretty quickly : 
```
banana
cake
apple
...
```

Unfortunately, the ```isFinal``` event is only triggered after around 2-3 seconds of silence, hence google interpret the audio input as if it's the same sentence and can change the recognized words to try to make a sentence which make sense.

It's working fine if I just end and re-start the recognition stream, but since google pricing rounded all the query to 15 seconds, i better use the same query for all those words. 

Would it be possible to make a silence threshold configurable when starting the stream ? Or manually trigger the ```isFinal``` event ?

Thank you

**Comment by munkhuushmgl** [comment]
@MadyAkira Would you mind sharing your code snippet used for this? 
Second question: Have you tried changing `single_utterance` flag to see if you can get quicker response?

**Comment by munkhuushmgl** [comment]
Due to inactivity, Im closing this issue.

Feel free to reopen
