### ISSUE TITLE
IsFinal never became true even though I stopped speaking when I used mobile phone with 'ko-KR' language

### ISSUE THREAD

**Issue by keunoklim** [googleapis/nodejs-speech#649]
I used @google-cloud/speech' npm to use STT service in google. 
When I used my mobile phone to provide audio for STT with 'ko-KR' , IsFinal never became true.
If I used my softphone in my PC, isFinal became true when I stopped talking.
Also IsFinal worked fine with 'en-US' when I used mobile phone.
Only problem happened combination mobile phone and 'ko-KR'.
Please help me solve the problem

**Comment by b-loved-dreamer** [comment]
Hi @keunoklim — without looking at the code you're using to access the service is difficult to diagnose the underlying problem. However, you can take a look at the [docs](https://cloud.google.com/speech-to-text/docs/languages) to find out how you can modify your ```config``` to make it work on your phone. Please see [this](https://cloud.google.com/speech-to-text/docs/phone-model).

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
