### ISSUE TITLE
Language code en-GB not working on infinite streaming example

### ISSUE THREAD

**Issue by drnickyoung** [googleapis/nodejs-speech#651]
Hi,

Running both MicrophoneStream and infiniteStreaming work fine after cloning the repository. Changing the language to en-GB on the MicrophoneStream sample works, albeit with several seconds of latency.  However infiniteStreaming with en-GB just sits there not finalising the translation.  I have tried the language from the command line and by changing the default in the code.  Am I missing something here?  This is the code out of the box, nothing changed other than trying to switch language.

#### Environment details

  - OS: MacOS 10.15.6
  - Node.js version: v14.11.0
  - npm version: 6.14.8
  - `@google-cloud/speech` version: 4.1.3

#### Steps to reproduce

  1. clone the repository
  2. setup export (API credentials, etc...)
  3. Run       node samples/infiniteStreaming.js infiniteStream -l en-GB

**Comment by b-loved-dreamer** [comment]
Hi @drnickyoung for ```infiniteStreaming``` are you referring to [this sample](https://github.com/googleapis/nodejs-speech/blob/master/samples/infiniteStreaming.js)?

**Comment by drnickyoung** [comment]
Hi @b-loved-dreamer,

yes that's the example. Sorry should have pointed to that in the original post.

Nick

**Comment by b-loved-dreamer** [comment]
Hi @drnickyoung, I've recently retried this issue with ```@google-cloud/speech``` version 2.0.0 and noticed the behavior with the ```en-GB``` went away. Please, give a try and confirm what you see. Thank you.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
