### ISSUE TITLE
i am trying to install (npm install @google-cloud/speech) library in to angular8 project

### ISSUE THREAD

**Issue by avinash9008** [googleapis/nodejs-speech#652]
but getting error like this ....
please help us 

ERROR in node_modules/@google-cloud/speech/build/src/v1/speech_client.d.ts(68,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1/speech_client.d.ts(73,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1/speech_client.d.ts(77,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1/speech_client.d.ts(82,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1p1beta1/speech_client.d.ts(71,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1p1beta1/speech_client.d.ts(76,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1p1beta1/speech_client.d.ts(80,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@google-cloud/speech/build/src/v1p1beta1/speech_client.d.ts(85,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-auth-library/build/src/auth/googleauth.d.ts(62,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-gax/build/src/fallback.d.ts(119,10): error TS1141: String literal expected.
    node_modules/google-gax/build/src/fallback.d.ts(119,13): error TS2304: Cannot find name 'protobufMinimal'.
    node_modules/google-gax/build/src/fallback.d.ts(119,29): error TS2304: Cannot find name 'from'.
    node_modules/google-gax/build/src/iamService.d.ts(45,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-gax/build/src/iamService.d.ts(50,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-gax/build/src/iamService.d.ts(54,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-gax/build/src/iamService.d.ts(59,16): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/google-gax/build/src/index.d.ts(47,10): error TS1141: String literal expected.
    node_modules/google-gax/build/src/index.d.ts(47,13): error TS2304: Cannot find name 'protobufMinimal'.
    node_modules/google-gax/build/src/index.d.ts(47,29): error TS2304: Cannot find name 'from'.
    node_modules/google-gax/build/src/operationsClient.d.ts(246,111): error TS2304: Cannot find name 'AsyncIterable'.
    node_modules/google-gax/build/src/paginationCalls/pageDescriptor.d.ts(41,83): error TS2304: Cannot find name 'AsyncIterable'.
    node_modules/google-gax/build/src/paginationCalls/pageDescriptor.d.ts(42,84): error TS2304: Cannot find name 'AsyncIterable'.
    node_modules/gtoken/build/src/index.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/gtoken/build/src/index.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/gtoken/build/src/index.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/gtoken/build/src/index.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by b-loved-dreamer** [comment]
Hi @avinash9008, we will need all available details in order to repro this error. From the title of this issue I can see that you're working with Angular and Node. We need more information to help you.

**Comment by b-loved-dreamer** [comment]
Closing this issue due to lack of clarity.
