### ISSUE TITLE
Recognition stops after a 2s pause when using recognize speech with metadata

### ISSUE THREAD

**Issue by urosran** [googleapis/nodejs-speech#667]
1) Is this a client library issue or a product issue?
Unsure how would you classify this - I'm setting the metadata but it yields no change in behaviour yet I have no way of figuring out if the problem is with the library or the cloud service

2) Did someone already solve this?
Not really

3) Do you have a support contract?
No

#### Environment details

  - OS: Windows 10
  - Node.js version: v14.2.0
  - npm version: 6.14.4
  - `@google-cloud/speech` version: "^3.3.1"

#### Steps to reproduce

  1. Install the library and follow the tutorial provided in the readme of this library
  2. Record 2 sentences with 2-3s pause in between them
  3. You will get only the first sentence recognized and not the second 

My code: 
`const speech = require("@google-cloud/speech").v1p1beta1;

        const fs = require("fs");
        let client = undefined;
        try {
            // Creates a client
            client = new speech.SpeechClient();
            console.log("filePathIn: ", filePathIn)

            // Get the WAV file path
            let WAVfile = null
            try {
                WAVfile = await linear16(filePathIn, "./output1.wav");
            } catch (e) {
                redLog(e, 'wav file conversion')
            }

            const file = fs.readFileSync(WAVfile);
            // const audioBytes = ;
            const audio = {
                content: file.toString("base64")
            };
            const recognitionMetadata = {
                interactionType: 'DICTATION',
                microphoneDistance: 'NEARFIELD',
                recordingDeviceType: 'SMARTPHONE',
                recordingDeviceName: 'Pixel 2 XL',
                industryNaicsCodeOfAudio: 519190,
            };
            // The audio file's encoding, sample rate in hertz, and BCP-47 language code
            const config = {
                encoding: "LINEAR16",
                sampleRateHertz: 16000,
                languageCode: "en-US",
                metadata: recognitionMetadata,
                model: 'phone_call'

            };
            const request = {
                audio: audio,
                config: config,
                single_utterance: false
            };

 response = await client.recognize(request).catch(error => console.log("google err: ", error));
                    greenLog(response)
`

Thanks guys!

**Comment by urosran** [comment]
Submitted an issue with the receiving side of the API call too, because not sure if the metadata is not sent correctly or there is an issue with the interpretation. Here is the link to the issue submitted to the Cloud Speech-To-Text team https://issuetracker.google.com/issues/172088167

**Comment by b-loved-dreamer** [comment]
Hi @urosran, I noticed in your configuration object you're not setting enabling the use of enhanced models with the ```useEnhanced```. Please review the [documentation](https://cloud.google.com/speech-to-text/docs/enhanced-models#speech_transcribe_enhanced_model-nodejs) for further details. 

Your ```config```:

```
        const config = {
            encoding: "LINEAR16",
            sampleRateHertz: 16000,
            languageCode: "en-US",
            metadata: recognitionMetadata,
            useEnhanced: true,
            model: 'phone_call'
        };
```

I tried to repro using your code and it wasn’t working because of the missing ```useEnhanced```. I got the following results after this change: 

```
results {
  alternatives {
    transcript: "I am from Seattle"
    confidence: 0.938856303691864
  }
  language_code: "en-gb"
}
results {
  alternatives {
    transcript: " this is an amazing place"
    confidence: 0.9338411688804626
  }
  language_code: "en-gb"
}
```
Notice the space before the second transcription. I recorded the phrases with 3s between them. 

 Please try this and let me know if it works

**Comment by urosran** [comment]
@b-loved-dreamer Thank you very much for the answer! I can confirm that this does indeed work. FYI as an end-user,  alternatives sounds as if we're getting different interpretations of the same input with their own confidence intervals rather than a transcription of each sentence. 

Thanks again for responding so quickly! You guys are amazing 😊😊😊
