### ISSUE TITLE
Getting Empty Result !!

### ISSUE THREAD

**Issue by gobindabd** [googleapis/nodejs-speech#671]
I am getting an empty string from Google speech API. From the other side sending live audio stream

here is my code 
```js
var cluster = require( "cluster" ); //Require the cluster module
var http = require( "http" ); //Require the http module
var ws = require( "ws" ).Server; //Require the WebSocket server module

//GOOGLE START
const speech = require('@google-cloud/speech');
const client = new speech.SpeechClient({keyFilename: '/usr/local/node_programs/service_account_file.json'});


const encoding = 'MULAW';
const sampleRateHertz = 8000;
const languageCode = 'en-GB';
const single_utterance = true;


const config = {
	encoding: encoding,
	sampleRateHertz: sampleRateHertz,
	languageCode: languageCode,
};

const audio = {
	content: null
}

async function main() 
{
	const [response] = await client.recognize({audio: audio,config: config})
	const transcription = response.results
	.map(result => result.alternatives[0].transcript)
	.join('\n');
	console.log(`Transcription: ${transcription}`);
}

//GOOGLE END

var workers = new Array();

if( cluster.isMaster )
{
	var cpus = require( "os" ).cpus().length;
	for( var i = 0; i < cpus; i ++)
	{
		var thread = cluster.fork();
		thread.on("message", function( message )
		{
			workers.forEach( function( worker )
			{
				if( worker.process.pid != message.pid )
				{
					worker.send( message.msg );
				}
			});
		});
		workers.push( thread );
	}
	return;
}

var server = http.createServer().listen( 8080 );
var wss = new ws( {server: server} );

var connections = new Array();

process.on( "message", function( message )
{
	connections.forEach( function( ws ){
	ws.send( message );
	});
});

wss.on( "connection", function( ws ){
	console.log((new Date()) + ' Connection accepted process id'+ process.pid + ' - Protocol Version ' + ws.webSocketVersion);

//ws.send( "Connected to #"+ process.pid );

ws.on( "message", function( message ){

audio.content = message
console.log(audio.content);

main().catch(console.error);

connections.forEach( function( otherWs ){
if( otherWs != ws ){
otherWs.send( message );
}
});
process.send( {pid: process.pid, msg: message} );
});
ws.on( "close", function(){
var index = connections.indexOf( ws );
connections.splice( index, 1 );
});
connections.push( ws );
});
```

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-error-reporting/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/error-reporting` version:

#### Steps to reproduce

  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @gobindabd, thank you for using our service. Without looking at your client code feeding the live audio stream is difficult to diagnose your problem. However, I think the problem here might be the logistics of how you send the audio data from the client to the server and how that data needs to be formatted so that it can be processed by the service. Additionally, if your trying to transcribe live stream audio data, you'll want to use the [streamingRecognize](https://cloud.google.com/speech-to-text/docs/streaming-recognize#speech-streaming-recognize-nodejs) instead.

**Comment by b-loved-dreamer** [comment]
Please reopen if needed.
