### ISSUE TITLE
Running checkLongRunningRecognizeProgress reach the 900 requet/miniute quota limit

### ISSUE THREAD

**Issue by geosigno** [googleapis/nodejs-speech#677]
After initializing a `longRunningRecognize` request, while waiting for the promise to be resolved, I'm running the `checkLongRunningRecognizeProgress` every 10 seconds to get a status and update the progression bar.  

Even though I'm executing it every 10 seconds, I get my quota of 900 requests/minutes for getOperation that has been reached.

It's like the `getOperation` was initiating hundreds of requests, is that the case? If so, is there a way to only have one request every x seconds?

**Comment by alexander-fenster** [comment]
@geosigno Thank you for the report. Can you please share your code? If I'm reading our code correctly, the `Operation` object returned by `checkLongRunningRecognizeProgress` will only poll for updates if it has a listener on its `"complete"` event, which is not the case by default.  The listener to `"complete"` event appears if you call the `.promise()` method, which you should not do if you only want to check the status once.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
