### ISSUE TITLE
Transcription for video/webm files are empty, while it's working on Google cloud "Try" page

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-speech#686]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-speech/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS:
  - Node.js version: 14
  - npm version: 6
  - `@google-cloud/speech` version: 4.1.5

#### Steps to reproduce

In [https://cloud.google.com/speech-to-text/](https://cloud.google.com/speech-to-text/) section "Put Speech-to-Text into action", if you upload a webm video file (which is recorded by web cam, a sample is attached as zip to this ticket) it will transcribe correctly and no issue (see below screenshot), 

![image](https://user-images.githubusercontent.com/10086092/102719561-cd43f580-42bc-11eb-82f6-5b25444e5bbc.png)

But in the nodejs client if you pass same file it doesn't work as expected and will result `{ results: [] }`

  1. Clone this repository
  2. Open quickstart.js
  3. change line 28 to `const fileName = './resources/selfie-video.webm';`
  4. Unzip attached file and add it to resources folder
  5. Run `node quickstart.js`

I tried with both
`const speech = require('@google-cloud/speech');` 
and
`const speech = require('@google-cloud/speech').v1p1beta1;`

Thanks!
[selfie-video.zip](https://github.com/googleapis/nodejs-speech/files/5721233/selfie-video.zip)

**Comment by b-loved-dreamer** [comment]
Hi @RezaRahmati, please follow steps [here](https://cloud.google.com/speech-to-text/docs/video-model) to transcribe your video.

**Comment by RezaRahmati** [comment]
@b-loved-dreamer thank you, so what I understand is to convert video to audio before calling the api, and if I understand correctly the api explorer page does it automatically?

**Comment by b-loved-dreamer** [comment]
Hi @RezaRahmati. The Demo uses a customized strategy for demonstrating the use of the service. This is decoupled from our client libraries and is not intended to be used for production. Please follow steps to prepare your audio data as explained in the shared link.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
