### ISSUE TITLE
Error: spawn sox ENOENT in Windows. 

### ISSUE THREAD

**Issue by crazylazylife** [googleapis/nodejs-speech#693]
Was trying to execute the nodejs code in my local machine for transcribing infinte streaming audio. I have followed all the necessary quickstart steps, but ran into this error

```
Listening, press Ctrl+C to stop.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn sox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn sox',
  path: 'sox',
  spawnargs: [
    '--default-device',
    '--no-show-progress',
    '--rate',
    16000,
    '--channels',
    1,
    '--encoding',
    'signed-integer',
    '--bits',
    '16',
    '--type',
    'wav',
    '-'
  ]
}
```

Upon further google search I found that `spawn sox` command doesn't work in Windows. Am I doing something wrong here?

#### Environment details

  - OS: Windows
  - Node.js version: 12.18.4
  - npm version: 6.14.6
  - `@google-cloud/speech` version: 4.2.0
  - sox: 14.4.2. Path variable is also set.

**Comment by munkhuushmgl** [comment]
From what I can tell, looks like you do not have `sox` installed in your environment

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
