### ISSUE TITLE
failed to find documentation either on github or on the documentation website regarding client library taking care of long running streams "chunking"

### ISSUE THREAD

**Issue by sivang** [googleapis/nodejs-speech#702]
A while ago, I received an email update about that the user of the client API library does not need to worry anymore about splitting audio to chunks to workaround the streaming audio duration limit and when there's silence.

I think it was in one of the APIs newsletters or off a github issue and I cannot remember.

As such this is not a a bug report per se, but rather a bug report about having those feature improvement of the client libraries documented well somewhere (I couldn't find any mention of this in the changelog).

Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @sivang — It would be helpful if you can provide at least one source for the newly launched  ```Speech``` client API so that we can a little more context. I will investigate internally in the meantime. Let's get this sorted out!

**Comment by sivang** [comment]
> Hi @sivang — It would be helpful if you can provide at least one source for the newly launched `Speech` client API so that we can a little more context. I will investigate internally in the meantime. Let's get this sorted out!

So I wish I was able to recall where I got this information, I vividly remember it was via an email update either from github or off the mailing list or some such - but that's exactly why I created this issue, as I tried tracking it back (it was ~6 months already).

Also I may have not been fully accurate in the original note, I believe this was an improvement to the client library resulting from an improvement to the API, relieving the calling code from worrying about all sorts of house keeping, so AFAIR things like ie like Longtime elapsed without audio and Resource exhausted error.

I now badly wish I had put that email update note  aside somewhere for when I will have returned to work on my code :)

**Comment by b-loved-dreamer** [comment]
Hi @sivang I tried to find specific information about this documentation but I could not find any. If you can provide more details so I can further direct my research that'd be great.

**Comment by b-loved-dreamer** [comment]
I found these two resources: 
https://googleapis.dev/nodejs/speech/latest/
https://github.com/googleapis/nodejs-speech

**Comment by b-loved-dreamer** [comment]
I am going to close this issue due to inactivity. Please feel free to reopen it if you need to.
