### ISSUE TITLE
Infinite Streaming Fail with sever API request error Error: 14 UNAVAILABLE: 408:Request Timeout

### ISSUE THREAD

**Issue by abramovi** [googleapis/nodejs-speech#715]
I am running **infiniteStreaming.js** and after several minute of transcription I am getting below error.

> 290000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
580000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
870000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
1160000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
1450000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
1740000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
2030000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
2320000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
2610000: RESTARTING REQUEST
API request error Error: 14 UNAVAILABLE: 408:Request Timeout
API request error Error: Cannot call write after a stream was destroyed
2900000: RESTARTING REQUEST

**Comment by b-loved-dreamer** [comment]
Hi @abramovi  — are you using the ```infiniteStreaming.js``` as is or are you adding custom logic to the sample? If you can please provide a bit more information, including a code snippet, that'd be useful.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
