### ISSUE TITLE
Typescript error "Type 'string' is not assignable to type 'AudioEncoding'"

### ISSUE THREAD

**Issue by mnebuerquo** [googleapis/nodejs-speech#716]
Typescript doesn't want to compile this because the string value isn't considered the same type as the enum value, even though the strings are equal.

```
error TS2345: Argument of type '{ config: { encoding: string; sampleRateHertz: number; languageCode: string; }; interimResults: boolean; }' is not assignable to parameter of type 'google.cloud.speech.v1.IStreamingRecognitionConfig | google.cloud.speech.v1p1beta1.IStreamingRecognitionConfig'.
Type '{ config: { encoding: string; sampleRateHertz: number; languageCode: string; }; interimResults: boolean; }' is not assignable to type 'IStreamingRecognitionConfig'.
The types of 'config.encoding' are incompatible between these types.
Type 'string' is not assignable to type '"LINEAR16" | "ENCODING_UNSPECIFIED" | "FLAC" | "MULAW" | "AMR" | "AMR_WB" | "OGG_OPUS" | "SPEEX_WITH_HEADER_BYTE" | AudioEncoding | "MP3"'.
```

This is the same problem as reported in text-to-speech:
https://github.com/googleapis/nodejs-text-to-speech/issues/314

If I could import the enum type from somewhere, that would work around the problem. There was a workaround suggested in the other issue, so maybe a similar one would work in this package?

This is apparently fixed in text-to-speech: https://github.com/googleapis/nodejs-text-to-speech/pull/331/files

**Comment by mnebuerquo** [comment]
Looks like it might be working if I treat that as `any`:
```
  const request = {
    config: {
      encoding: encoding as any,
      sampleRateHertz: sampleRateHertz,
      languageCode: languageCode,
    },
    interimResults: false,
  }
```

**Comment by laurentlp** [comment]
@mnebuerquo I know this isn't ideal, but you can do something like this:

```typescript
import { protos } from '@google-cloud/speech'

type IRecognizeRequest = protos.google.cloud.speech.v1.IRecognizeRequest

const config: IRecognizeRequest['config'] = {
    encoding: 'LINEAR16',
    sampleRateHertz: 16000,
    languageCode: 'en-US'
}

```

**Comment by b-loved-dreamer** [comment]
Hi @mnebuerquo — thank you for filing this issue. We will consider this a feature request and see if a fix similar to the one you referenced is attainable in this case. I recommend checking online (```Stack-OverFlow```) for possible solutions for your specific situation. If you experience any issues with the client, service, or the sample, please file an issue accordingly. 

We have not heard back from you. We are unable to proceed with this issue until then, so we are closing it.

**Comment by mnebuerquo** [comment]
@b-loved-dreamer , thanks for looking into this. I worked around it by just typing that field as `any` instead of `string`. It's not ideal, but I'm not a typescript purist by any stretch. I mainly wanted to document this for the next person who hits it so the google search tells them they're not the only one seeing the error and that it's not something they're doing wrong. You're welcome, future-people!

**Comment by b-loved-dreamer** [comment]
Thank you @mnebuerquo!
