### ISSUE TITLE
Make it work with Angular

### ISSUE THREAD

**Issue by ranouf** [googleapis/nodejs-speech#72]
Hi,

I installed the npm package:

`npm install --save @google-cloud/speech`

I m curious to know if it possible to make it work with Angular 5 and how to do it?

I read an article about including a js library in an angular project:
[https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af](https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af)

But when I add this code:

```
import * as _ from '@google-cloud/speech';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor() {
   const client = new _.speech.SpeechClient();
}
```

With `npm start` I have this error:

> ERROR in ./node_modules/google-gax/lib/operations_client.js
> Module not found: Error: Can't resolve './operations_client_config' in 'GoogleSpeechTest\src\client\node_modules\google-gax\lib'
> ERROR in ./node_modules/google-gax/index.js
> Module not found: Error: Can't resolve './package' in 'GoogleSpeechTest\src\client\node_modules\google-gax'
> ERROR in ./node_modules/@google-cloud/speech/src/v1/speech_client.js
> Module not found: Error: Can't resolve './speech_client_config' in 'GoogleSpeechTest\src\client\node_modules\@google-cloud\speech\src\v1'
> ERROR in ./node_modules/@google-cloud/speech/src/v1p1beta1/speech_client.js
> Module not found: Error: Can't resolve './speech_client_config' in 'GoogleSpeechTest\src\client\node_modules\@google-cloud\speech\src\v1p1beta1'
> ERROR in ./node_modules/gtoken/node_modules/mime/index.js
> Module not found: Error: Can't resolve './types/other' in 'GoogleSpeechTest\src\client\node_modules\gtoken\node_modules\mime'
> ERROR in ./node_modules/gtoken/node_modules/mime/index.js
> Module not found: Error: Can't resolve './types/standard' in 'GoogleSpeechTest\src\client\node_modules\gtoken\node_modules\mime'
> ERROR in ./node_modules/detect-libc/lib/detect-libc.js
> Module not found: Error: Can't resolve 'child_process' in 'GoogleSpeechTest\src\client\node_modules\detect-libc\lib'
> ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js
> Module not found: Error: Can't resolve 'child_process' in 'GoogleSpeechTest\src\client\node_modules\google-auth-library\build\src\auth'

**Comment by ranouf** [comment]
Hi,

Is there someone who can help me?

**Comment by stephenplusplus** [comment]
[This issue](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1821) on our common repo might help get past some hurdles, but unfortunately, our client libraries are not designed with browser compatibility in mind.

**Comment by avinash9008** [comment]
@ranouf 

please help me i am also facing same issue with npm install --save @google-cloud/speech in angular
