### ISSUE TITLE
Passing CallOptions to streamingRecognize doesn't work

### ISSUE THREAD

**Issue by w4-sjcho** [googleapis/nodejs-speech#723]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
I don't think so

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Linux
  - Node.js version: v14.15.5
  - npm version: 6.14.11
  - `@google-cloud/speech` version: 4.4.0

#### Steps to reproduce

Try calling SpeechClient.streamingRecognize with CallOptions set.

If you look at [`speech_client.ts#L438`](https://github.com/googleapis/nodejs-speech/blob/master/src/v1/speech_client.ts#L438), `this.innerApiCalls.streamingRecognize` is a function of type [`GaxCall`](https://googleapis.dev/nodejs/google-gax/latest/interfaces/GaxCall.html), whose 2nd argument is `CallOptions`, not the first. But `speech_client.ts#L438` passes `CallOptions` as the 1st argument, causing the bug. The 1st argument is just ignored by [`StreamingApiCaller`](https://googleapis.dev/nodejs/google-gax/latest/classes/StreamingApiCaller.html#source).

**Comment by alexander-fenster** [comment]
Reassigning to @summer-ji-eng.  It looks like our typings for the streaming calls might be incorrect.  Could you please schedule this for some time next sprint?  Thank you!

**Comment by alexander-fenster** [comment]
@summer-ji-eng The motivation is that `streamingRecognize` is a bi-di streaming method that does not have the first parameter. The requests come via the stream.

Can I bother you writing a test code for Showcase `chat` method and check if the option indeed can be passed to the bi-di streaming method?

**Comment by summer-ji-eng** [comment]
> @summer-ji-eng The motivation is that `streamingRecognize` is a bi-di streaming method that does not have the first parameter. The requests come via the stream.
> 
> Can I bother you writing a test code for Showcase `chat` method and check if the option indeed can be passed to the bi-di streaming method?

Sure. Thanks for looking at this. I will writing a test code and post link if any related PR here.

**Comment by summer-ji-eng** [comment]
fixed in https://github.com/googleapis/gapic-generator-typescript/pull/1066
