### ISSUE TITLE
Throw error if languageCode is invalid

### ISSUE THREAD

**Issue by ahojukka5** [googleapis/nodejs-speech#726]
An error should be thrown if languageCode is not recognized. Currently, if languageCode is mistyped, e.g. `eu-US` instead of `en-US`, speech recognition just stops working and it's hard to find out what's the problem.

**Comment by b-loved-dreamer** [comment]
Hi @ahojukka5 — we assume users will make sure to check their config settings before packaging and sending a request to the server. Please let me know if I can answer more questions related to the service or the client.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue.
