### ISSUE TITLE
Is "End of Speech Sensitivity" supported?

### ISSUE THREAD

**Issue by bivas6** [googleapis/nodejs-speech#765]
Hi,

We noticed that it takes the 'recognizer' to return a final recognition about 1 sec of silence after end of speech.
We would like to control this silence period by a parameter.
Is that possible?

Thanks

**Comment by b-loved-dreamer** [comment]
Hi @bivas6, thank you for filling this issue. Currently there is not a way to manipulate this aspect of the transcription process. We will consider this a feature request. Please visit [this](https://cloud.google.com/support/docs/issue-trackers) site to report a feature request.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
