### ISSUE TITLE
Support for web

### ISSUE THREAD

**Issue by tomtobac** [googleapis/nodejs-speech#776]
Hello 👋 

I am trying to understand if there is any support for work directly from the browser. I saw the example of [google with the microphone](https://cloud.google.com/speech-to-text) and it's using websockets to achieve it. But if I try to use it in a browser with a bundler im getting the following error:
```
Error: You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client form google-auth-library.
```
Does that mean that i will need to set up a "[login](https://github.com/googleapis/google-auth-library-nodejs#oauth2)" button with google with a callback to my application in order to get an auth instance, right?

My use case would be a internal webpage (SPA) that it loads directly authenticated and can make request to google-speech-api directly from the browser

Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @tomtobac — thank you for posting your concern. When you say support from the browser, are you referring to a client application? And also, are you asking if there's support currently for usage of the ```speech``` service from a client application? Also, please can you share a snippet of your code. Please explain what exactly you are trying to accomplish.

**Comment by tomtobac** [comment]
Yes, @b-loved-dreamer, I am trying to use it directly in the browser as a client application. I saw that when you import the `@google-cloud/speech` library in the browser it show the above error (`You need to pass auth instance...`). My question its if there is any way to use it without the `OAuth2Client`, just with a service account. 

My use case in inhouse application which has access to a voice stream of a call and for security purposes we want do it directly from the browser

**Comment by b-loved-dreamer** [comment]
The ```@google-cloud/speech``` client is meant to be used in the backend. I do not have the details of your implementation, so I would not be able to help much with the browser side of your concern. If you have a backend and that's where you're the error, you could try to pass the service account key when constructing the client. Check this [issue  ](https://github.com/googleapis/nodejs-vision/issues/489). 

https://blog.softwaremill.com/how-to-use-googles-speech-to-text-in-a-web-application-working-example-a4b64c61f133

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
