### ISSUE TITLE
"12 UNIMPLEMENTED: Method not found." when cancelling a long running speech to text operation

### ISSUE THREAD

**Issue by roballsopp** [googleapis/nodejs-speech#779]
#### Environment details

  - OS: Windows 11
  - Node.js version: 14.14.0
  - npm version: 6.14.8
  - `@google-cloud/speech` version: 4.5.4 (I'm using v1p1beta1)

#### Steps to reproduce
1. Start a long running speech to text job with `speechClient.longRunningRecognize(...)`
2. Attempt to cancel the operation with:
```javascript
const lro = await speechClient.checkLongRunningRecognizeProgress(operationId);

if (lro.done) {
	return;
}

await lro.cancel(); // throws error: "12 UNIMPLEMENTED: Method not found."
```
Is this the correct way to cancel a speech to text op? If so, is this a bug? If not, how should it be done?

**Comment by bcoe** [comment]
@roballsopp looking at [the helpers](https://github.com/googleapis/gax-nodejs/blob/master/src/longRunningCalls/longrunning.ts#L131) I believe `cancel()` is the right method call, I'm not sure what's happening here.

@summer-ji-eng anything I'm missing, with regards to LRO behavior?

**Comment by b-loved-dreamer** [comment]
Hi @roballsopp — I have verified that this endpoint is in fact unimplemented, as the returned error message indicates. This is a service issue for which you can file a report in the service [portal](https://cloud.google.com/speech-to-text).

**Comment by roballsopp** [comment]
I've opened a ticket here: https://issuetracker.google.com/issues/195805183

**Comment by roballsopp** [comment]
Looks like this is intended behavior, and the engineering team over there has no plans to support cancelling speech to text operations.

**Comment by b-loved-dreamer** [comment]
@roballsopp — thank you for the update. The transcription process is really fast so I imagine that trying to cancel it would have no effect in most cases. Of course it can stop altogether on some error. 

I believe these findings makeup for a satisfying response to your concern. I will now go ahead and close this issue. Please feel free to reopen if you think there is more to be added about this situation.
