### ISSUE TITLE
How to get speakertag from longRunningRecognize?

### ISSUE THREAD

**Issue by sasikanth513** [googleapis/nodejs-speech#81]
#### Environment details

  - OS: Mac
  - Node.js version: v8.11.1
  - npm version: 5.6.0
  - `@google-cloud/speech` version: 1.5.0

#### Steps to reproduce

  1. Run any longRunningRecognize process
  2. In the response there is no information about speakertag

This is the code i'm using

```
    const speech = require('@google-cloud/speech');

    const client = new speech.SpeechClient({
      projectId: Meteor.settings.private.googleCloud.projectId,
      keyFilename: getFilePath('google-cloud.json')
    });

	const config = {
      "enableWordTimeOffsets": true,
      "encoding": "WAV",
      "languageCode": "en-US",
      "sampleRateHertz": 44100,
      "model": "video"
    };

    const audio = {
      uri: "gs://my-project-name/jeff_bezos_1_mono.wav",
    };

    const options = {
      config: config,
      audio: audio,
    };

    client
      .longRunningRecognize(options)
      .then(data => {
        const operation = data[0];
        console.log('got a promise representation', data);

        const errorHandler = err => {
          console.log(err);
          throw(err)
        }
        const completeHandler = longRRResponse => {
          console.log('**** response ****');
          console.log(JSON.stringify(longRRResponse, null, 2));
        }
        const progressHandler = (metadata, apiResponse) => {
          console.log('progress ', metadata);
        }
        operation.on('error', errorHandler)
        operation.on('complete', completeHandler)
        operation.on('progress', progressHandler)
      })
      .catch(err => {
        console.error('ERROR:', err);
        fs.unlink(name);
      });
```

this is the following response I got back

```
{
  "results": [
    {
      "alternatives": [
        {
          "words": [
            {
              "startTime": {
                "nanos": 100000000
              },
              "endTime": {
                "nanos": 700000000
              },
              "word": "your"
            },
            .
            .
            .
          ],
          "transcript": "your goal is to be the largest online and you are retailer in the world beyond that what's the goal for our mission is Earth's most customer-centric company and I know what that mean I'll give you an example",
          "confidence": 0.9520494341850281
        }
      ]
    },
}
```

I did not find any information about `speakerTag`, how to get back `speakerTag` information?

In google api-explorer for recognize there is option to select speakerTag in the fields section
 
<img width="766" alt="screen shot 2018-05-24 at 10 20 17 am" src="https://user-images.githubusercontent.com/6153816/40465437-448007b6-5f3e-11e8-8fac-aa373c96493a.png">

Thanks!

**Comment by salilsethi** [comment]
This issue is open for 2 weeks. Any update?

**Comment by sirtorry** [comment]
are you asking about speaker diarization? if so, this feature is not yet available.

**Comment by crwilcox** [comment]
I spent some time looking into this with the help of @sirtorry. As he states speaker diarization isn't yet available. Also, the client libraries don't provide a mechanism to 'field mask' like the api explorer.

**Comment by yeya** [comment]
It does work in current beta version.
You can try it with `const client = new Speech.v1p1beta1.SpeechClient()`
You should add `enableSpeakerDiarization: true` to the config object.

I found the best documentation is [here](https://github.com/googleapis/nodejs-speech/blob/master/src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js)
