### ISSUE TITLE
We have some recording problem

### ISSUE THREAD

**Issue by bsanjaasuren** [googleapis/nodejs-speech#829]
We are using the nodejs-speech library for a call transcription feature on our web application. But we have noticed an issue that it's also converting the caller's voice when I set loudspeaker mode. Which leads to duplication on both sides. I think it depends on the library that records from the microphone. But If it is possible could you please suggest to us the best way to solve that problem?

**Comment by meredithslota** [comment]
The library will transcribe the audio it's given — without knowing more about your setup, it's tricky to debug, but possibly this overview will be of assistance? https://cloud.google.com/architecture/architecture-for-production-ready-live-transcription-tutorial
