### ISSUE TITLE
Relative links added to protos causing doc tests to fail

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-speech#833]
Links inside protos should be absolute URLs, so that they're appropriately linked to in generated reference documents. #825 introduces relative links, which causes doc tests to fail.

**Comment by meredithslota** [comment]
This looks like it was fixed in cl/440481666, and shows up as fixed here: https://github.com/googleapis/nodejs-speech/blob/main/protos/google/cloud/speech/v1p1beta1/cloud_speech_adaptation.proto Closing.
