### ISSUE TITLE
got "Internal error encountered."  with `adaptationClient.createCustomClass({/*...*/})`

### ISSUE THREAD

**Issue by okunishinishi** [googleapis/nodejs-speech#847]
#### Environment details

  - OS: macOS
  - Node.js version: v14.18.2
  - npm version: 6.14.15
  - `@google-cloud/speech` version: 4.9.0

#### Steps to reproduce

```js
await adaptationClient.createCustomClass({
     parent: `projects/${projectId}/locations/global/customClasses`,
     customClassId: 'helloworld',
     customClass: {
          items: [{ value: 'hello' }],
     }
})
```

and i got 

```console
Error: 13 INTERNAL: Internal error encountered.
    at Object.callErrorFromStatus (/Users/okuni/Projects/raisin-worker/packages/bot/node_modules/@google-cloud/speech/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/okuni/Projects/raisin-worker/packages/bot/node_modules/@google-cloud/speech/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/Users/okuni/Projects/raisin-worker/packages/bot/node_modules/@google-cloud/speech/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/okuni/Projects/raisin-worker/packages/bot/node_modules/@google-cloud/speech/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/okuni/Projects/raisin-worker/packages/bot/node_modules/@google-cloud/speech/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'Internal error encountered.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

what is wrong?

**Comment by kweinmeister** [comment]
I suggest trying out the [Model Adaptation test](https://github.com/googleapis/nodejs-speech/blob/main/samples/system-test/modelAdaptation.test.js), which invokes this [sample code](https://github.com/googleapis/nodejs-speech/blob/main/samples/modelAdaptation.js). If you are able to run that successfully, then try to adapt it to your configuration.

**Comment by okunishinishi** [comment]
@kweinmeister 

I tried [Model Adaptation test](https://github.com/googleapis/nodejs-speech/blob/main/samples/system-test/modelAdaptation.test.js), and got `7 PERMISSION_DENIED: Permission is denied.`

![Screen Shot 2022-02-05 at 10 13 39](https://user-images.githubusercontent.com/745662/152622942-4f533e79-3aa9-40ad-a7fc-14c4be0e7b10.png)


But i can create custom create class from browser with GUI

<img width="799" alt="Screen Shot 2022-02-05 at 10 15 15" src="https://user-images.githubusercontent.com/745662/152623001-1034a8bb-5191-4c8a-a0dc-5069a0487ce3.png">

**Comment by okunishinishi** [comment]
`parent` option is defined as

*  `projects/${projectId}/locations/${location}`  in the [sample code](https://github.com/googleapis/nodejs-speech/blob/main/samples/modelAdaptation.js#L31)
*  `projects/{project}/locations/{location}/customClasses` in the [reference document](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1p1beta1#createcustomclassrequest)

which is correct ?


![Screen Shot 2022-02-05 at 10 22 12](https://user-images.githubusercontent.com/745662/152623277-35f7cebb-8ce2-4f8c-b06e-2385c194e8d6.png)

![Screen Shot 2022-02-05 at 10 22 01](https://user-images.githubusercontent.com/745662/152623280-5a0ffd9a-e83f-4bf4-8957-7b600f0b5b7e.png)
