### ISSUE TITLE
updatePhraseSet Endpoint Utilization

### ISSUE THREAD

**Issue by craneabove** [googleapis/nodejs-speech#855]
#### Environment details

  - OS: MacOS Monterey
  - Node.js version: v15.14.0
  - npm version: 7.7.6
  - `@google-cloud/speech` version: 4.9.0

#### Issue

We are simply trying to utilize the adaptation client to first create a phrase set. This is now being done successfully. Initially we wasted a day trying to create a phrase set using the adaptation client because the documentation is incorrect. Please update the documentation to correct this [here](https://cloud.google.com/nodejs/docs/reference/speech/latest/speech/v1p1beta1.adaptationclient#_google_cloud_speech_v1p1beta1_AdaptationClient_createPhraseSet_member_1_https://cloud.google.com/nodejs/docs/reference/speech/latest/speech/v1p1beta1.adaptationclient#_google_cloud_speech_v1p1beta1_AdaptationClient_createPhraseSet_member_1_)

This line in the example:
```
The parent resource where this phrase set will be created. Format:
   *  `projects/{project}/locations/{location}/phraseSets`
```
SHOULD BE (remove `/phraseSets`):
```
The parent resource where this phrase set will be created. Format:
   *  `projects/{project}/locations/{location}`
```

Now that we can successfully create phrase sets we are struggling to _**update**_ them. The documented example [here](https://cloud.google.com/nodejs/docs/reference/speech/latest/speech/v1p1beta1.adaptationclient#_google_cloud_speech_v1p1beta1_AdaptationClient_updatePhraseSet_member_1_) does not demonstrate how the updateMask should be constructed, and in fact it is not even inserted into the `request` object for use in the call.

Any guidance on how to successfully perform an `updatePhraseSet` call would be greatly appreciated! And if I missed anything in the documentation I apologize!

Thanks!

**Comment by kweinmeister** [comment]
Thanks for passing on the feedback on the documentation. We'll have that reviewed.

Meanwhile, here are a couple resources that might help you get going:
*  The [REST API doc](https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/projects.locations.phraseSets/patch) and [example #3 in the docs](https://cloud.google.com/speech-to-text/docs/adaptation-model#improve_transcription_using_a_phraseset) showing how to update a phrase set. Note that `updateMask=phrases` and the payload used.
* Although it's for a different API, you can see a Node.js example to create an `updateMask` [here](https://cloud.google.com/dialogflow/es/docs/how/field-mask).

**Comment by craneabove** [comment]
@kweinmeister Thanks for your response! I'm not sure what we're still doing wrong, even after clues in both the references you gave 😅...we've structured the call quite a few different ways, all to no avail. The correct PhraseSet will be return by the call, but no updates occur. Here is how it's structured:

```javascript
  const phraseSet = {
    phrases: [
      {
        value: "pizza",
        boost: 10,
      },
      {
        value: "veggie burgers",
        boost: 10,
      },
    ],
    name:
      "projects/{project-id}/locations/global/phraseSets/test-update-phrase-set",
  };
  const updateMask = phraseSet.phrases;

  async function callUpdatePhraseSet() {

    const request = {
      phraseSet: phraseSet,
      updateMask: updateMask,
    };

    // Run request
    const response = await speechClient.updatePhraseSet(request);
    console.log(response);
  }
  callUpdatePhraseSet().catch((err) => {
    console.log("ERROR: " + err);
  });
```

**Comment by kweinmeister** [comment]
Hi @craneabove - I think you're getting close. I would look at `updateMask`: it looks like you're setting the mask to the new data, rather than the list of fields you want updated.

You can see that in the Dialogflow API example that the mask is set to a set of paths, or fields that act as a filter on what should be updated.

The CURL example is indicating the fields to be updated with the URL parameter `updateMask` set to `phrases`, and then provides the data itself with the `-d` parameter.

With the Dialogflow example in mind, I might try this (or something similar)?
```
const updateMask = {
  paths: ['phrases'],
};
```

Also, in case it's helpful, here's a [video](https://www.youtube.com/watch?v=W421BNZA_74) that explains the concept.

**Comment by craneabove** [comment]
@kweinmeister Thank you very much, that was the ticket! It's working perfectly now!
