### ISSUE TITLE
Add MP3 encoding in enum for request config

### ISSUE THREAD

**Issue by yonathan06** [googleapis/nodejs-speech#903]
- OS: linux
  - Node.js version: 16
  - `@google-cloud/speech` version: 4.10.2

#### Steps to reproduce

`google.cloud.speech.v1.RecognitionConfig.AudioEncoding` enum does not have `MP3` as an option, even though it is a valid encoding (had to add `//@ts-ignore` to assign `MP3` as value)
the current enum in the source code:
```TypeScript
enum AudioEncoding {
  ENCODING_UNSPECIFIED = 0,
  LINEAR16 = 1,
  FLAC = 2,
  MULAW = 3,
  AMR = 4,
  AMR_WB = 5,
  OGG_OPUS = 6,
  SPEEX_WITH_HEADER_BYTE = 7,
  WEBM_OPUS = 9
}
```

**Comment by alexander-fenster** [comment]
It does have `MP3` encoding in `v1p1beta1` version:

```ts
import * as speech from '@google-cloud/speech';
const client = new speech.v1p1beta1.SpeechClient();
```
