### ISSUE TITLE
Config for MP3 & "Phone call (Enhanced)" mode ?

### ISSUE THREAD

**Issue by tianalemesle** [googleapis/nodejs-speech#913]
Hello,

I'm trying to reproduce the following GUI settings :

![Screenshot from 2022-07-13 12-09-30](https://user-images.githubusercontent.com/72209627/178709717-00eaf968-fed6-45da-adfc-40d5e8cb7354.png)
![Screenshot from 2022-07-13 12-09-07](https://user-images.githubusercontent.com/72209627/178709720-47a9aae6-50db-4267-9708-7de1ddd475cd.png)

I've done this so far :
```js
import { SpeechClient } from '@google-cloud/speech';

(async () => {
    const client = new SpeechClient();
    await client.recognize({
        config: {
            sampleRateHertz: 48000,
            audioChannelCount: 1,
            enableSeparateRecognitionPerChannel: false,
            languageCode: 'fr-FR',
            useEnhanced: true
        }
    })
})().catch(console.error);
```

But, I don't know which `config.encoding` value matches *MP3* :
```ts
enum AudioEncoding {
    ENCODING_UNSPECIFIED = 0,
    LINEAR16 = 1,
    FLAC = 2,
    MULAW = 3,
    AMR = 4,
    AMR_WB = 5,
    OGG_OPUS = 6,
    SPEEX_WITH_HEADER_BYTE = 7,
    WEBM_OPUS = 9
}
```
I can't figure out how to set `config.model` to match *Phone call (Enhanced)* either :
```ts
interface IRecognitionConfig {
    model?: (string|null);
}
```
Thanks

**Comment by alexander-fenster** [comment]
Please try `v1p1beta1` version, it [supports](https://github.com/googleapis/nodejs-speech/blob/main/protos/google/cloud/speech/v1p1beta1/cloud_speech.proto#L245) `MP3`.

```ts
import * as speech from '@google-cloud/speech';
const client = new speech.v1p1beta1.SpeechClient();
```
