### ISSUE TITLE
v5.0.0 is not released on NPM

### ISSUE THREAD

**Issue by ahmedkandel** [googleapis/nodejs-speech#917]
Hi,

I'm trying to update to the latest version but on [NPM](https://www.npmjs.com/package/@google-cloud/speech) the lates version still 4.10.2

**Comment by meredithslota** [comment]
Thank you for filing this! I see 5.0.1 and recently, 5.0.2 on NPM but you are right, 5.0.0 is still not there. Reclassifying as a bug, it looks like something went wrong with our release process.

**Comment by bcoe** [comment]
`v5.0.0` has been published.
