### ISSUE TITLE
Setting config.enableSpokenPunctuation to true => I received an answer that an object is expected instead

### ISSUE THREAD

**Issue by DanielChappuis** [googleapis/nodejs-speech#927]
I am using the Google STT API with Node JS. When I set the following config:

`config = {
  encoding: 'LINEAR16',
  sampleRateHertz: 16000,
  languageCode: 'fr-FR',
  enableWordConfidence: true,
  enableWordTimeOffsets: false,
  maxAlternatives: 4,
  useEnhanced: false,
  model: 'latest_short',
  enableAutomaticPunctuation: true,
  enableSpokenPunctuation: true,
  enableSpokenEmojis: true
}`

Then, I receive the following error from Google STT API:

`Error: 13 INTERNAL: Request message serialization failure: .google.cloud.speech.v1.RecognitionConfig.enableSpokenPunctuation: object expected`

I don't understand this error because in the documentation [here](https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig), the 'enableSpokenPunctuation' variable is supposed to be a boolean value not an object.

What's going on here?

**Comment by alexander-fenster** [comment]
Oops, this is something we would need to improve.  Currently in the protos, the parameter is defined not as `bool` but as [`google.protobuf.BoolValue`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wrappers.proto#L104-L107):

```proto
  google.protobuf.BoolValue enable_spoken_punctuation = 22;
```

which means the proper way to pass it would be

```ts
{
  ...
  enableSpokenPunctuation: {
    value: false;
  },
}
```

If you use TypeScript types, it should suggest this usage. Unfortunately, at this point, "wrapper types" such as `BoolValue` are not supported by protobuf.js natively, so this weird syntax is required.

**Comment by DanielChappuis** [comment]
Ok thanks a lot for your answer.

I was using [this documentation](https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/RecognitionConfig) where the type is specified as "boolean".
